// Generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro from Redwood EDA, LLC.
// Redwood EDA, LLC does not claim intellectual property rights to this file and provides no warranty regarding its correctness or quality.


// For silencing unused signal messages.
`define BOGUS_USE(ignore)


`include "sandpiper_gen.vh"


genvar dmem, xreg;


//
// Signals declared top-level.
//

// For |cpu$alt_pc.
logic [63:0] CPU_alt_pc_a0,
             CPU_alt_pc_a1;

// For |cpu$alu_op2.
logic [63:0] CPU_alu_op2_a0;

// For |cpu$alu_result.
logic [63:0] CPU_alu_result_a0;

// For |cpu$alu_result32.
logic [63:0] CPU_alu_result32_a0;

// For |cpu$alu_result32_raw.
logic [31:0] CPU_alu_result32_raw_a0;

// For |cpu$alu_result64.
logic [63:0] CPU_alu_result64_a0;

// For |cpu$alu_sra64.
logic [63:0] CPU_alu_sra64_a0;

// For |cpu$alu_sraw32_wide.
logic [63:0] CPU_alu_sraw32_wide_a0;

// For |cpu$blt_signed.
logic CPU_blt_signed_a0;

// For |cpu$branch_taken.
logic CPU_branch_taken_a0;

// For |cpu$branch_target.
logic [63:0] CPU_branch_target_a0;

// For |cpu$cyc_cnt.
logic [31:0] CPU_cyc_cnt_a0,
             CPU_cyc_cnt_a1;

// For |cpu$dmem_new_word.
logic [63:0] CPU_dmem_new_word_a0,
             CPU_dmem_new_word_a1;

// For |cpu$funct3.
logic [2:0] CPU_funct3_a0;

// For |cpu$funct6.
logic [5:0] CPU_funct6_a0;

// For |cpu$funct7.
logic [6:0] CPU_funct7_a0;

// For |cpu$imm_b.
logic [63:0] CPU_imm_b_a0;

// For |cpu$imm_i.
logic [63:0] CPU_imm_i_a0;

// For |cpu$imm_j.
logic [63:0] CPU_imm_j_a0;

// For |cpu$imm_s.
logic [63:0] CPU_imm_s_a0;

// For |cpu$imm_u.
logic [63:0] CPU_imm_u_a0;

// For |cpu$instr.
logic [31:0] CPU_instr_a0;

// For |cpu$instr_elf.
logic [31:0] CPU_instr_elf_a0;

// For |cpu$instr_rom.
logic [31:0] CPU_instr_rom_a0;

// For |cpu$is_add.
logic CPU_is_add_a0;

// For |cpu$is_addi.
logic CPU_is_addi_a0;

// For |cpu$is_addiw.
logic CPU_is_addiw_a0;

// For |cpu$is_addw.
logic CPU_is_addw_a0;

// For |cpu$is_alu_imm.
logic CPU_is_alu_imm_a0;

// For |cpu$is_alu_immw.
logic CPU_is_alu_immw_a0;

// For |cpu$is_alu_reg.
logic CPU_is_alu_reg_a0;

// For |cpu$is_alu_regw.
logic CPU_is_alu_regw_a0;

// For |cpu$is_and.
logic CPU_is_and_a0;

// For |cpu$is_andi.
logic CPU_is_andi_a0;

// For |cpu$is_auipc.
logic CPU_is_auipc_a0;

// For |cpu$is_beq.
logic CPU_is_beq_a0;

// For |cpu$is_bge.
logic CPU_is_bge_a0;

// For |cpu$is_bgeu.
logic CPU_is_bgeu_a0;

// For |cpu$is_blt.
logic CPU_is_blt_a0;

// For |cpu$is_bltu.
logic CPU_is_bltu_a0;

// For |cpu$is_bne.
logic CPU_is_bne_a0;

// For |cpu$is_fence.
logic CPU_is_fence_a0;

// For |cpu$is_jal.
logic CPU_is_jal_a0;

// For |cpu$is_jalr.
logic CPU_is_jalr_a0;

// For |cpu$is_lb.
logic CPU_is_lb_a0;

// For |cpu$is_lbu.
logic CPU_is_lbu_a0;

// For |cpu$is_ld.
logic CPU_is_ld_a0;

// For |cpu$is_lh.
logic CPU_is_lh_a0;

// For |cpu$is_lhu.
logic CPU_is_lhu_a0;

// For |cpu$is_load.
logic CPU_is_load_a0;

// For |cpu$is_lui.
logic CPU_is_lui_a0;

// For |cpu$is_lw.
logic CPU_is_lw_a0;

// For |cpu$is_lwu.
logic CPU_is_lwu_a0;

// For |cpu$is_or.
logic CPU_is_or_a0;

// For |cpu$is_ori.
logic CPU_is_ori_a0;

// For |cpu$is_sb.
logic CPU_is_sb_a0;

// For |cpu$is_sd.
logic CPU_is_sd_a0;

// For |cpu$is_sh.
logic CPU_is_sh_a0;

// For |cpu$is_shift_imm.
logic CPU_is_shift_imm_a0;

// For |cpu$is_shift_immw.
logic CPU_is_shift_immw_a0;

// For |cpu$is_sll.
logic CPU_is_sll_a0;

// For |cpu$is_slli.
logic CPU_is_slli_a0;

// For |cpu$is_slliw.
logic CPU_is_slliw_a0;

// For |cpu$is_sllw.
logic CPU_is_sllw_a0;

// For |cpu$is_slt.
logic CPU_is_slt_a0;

// For |cpu$is_slti.
logic CPU_is_slti_a0;

// For |cpu$is_sltiu.
logic CPU_is_sltiu_a0;

// For |cpu$is_sltu.
logic CPU_is_sltu_a0;

// For |cpu$is_sra.
logic CPU_is_sra_a0;

// For |cpu$is_srai.
logic CPU_is_srai_a0;

// For |cpu$is_sraiw.
logic CPU_is_sraiw_a0;

// For |cpu$is_sraw.
logic CPU_is_sraw_a0;

// For |cpu$is_srl.
logic CPU_is_srl_a0;

// For |cpu$is_srli.
logic CPU_is_srli_a0;

// For |cpu$is_srliw.
logic CPU_is_srliw_a0;

// For |cpu$is_srlw.
logic CPU_is_srlw_a0;

// For |cpu$is_store.
logic CPU_is_store_a0,
      CPU_is_store_a1;

// For |cpu$is_sub.
logic CPU_is_sub_a0;

// For |cpu$is_subw.
logic CPU_is_subw_a0;

// For |cpu$is_sw.
logic CPU_is_sw_a0;

// For |cpu$is_w_op.
logic CPU_is_w_op_a0;

// For |cpu$is_xor.
logic CPU_is_xor_a0;

// For |cpu$is_xori.
logic CPU_is_xori_a0;

// For |cpu$jal_target.
logic [63:0] CPU_jal_target_a0;

// For |cpu$jalr_target.
logic [63:0] CPU_jalr_target_a0;

// For |cpu$load_data.
logic [63:0] CPU_load_data_a0;

// For |cpu$lt_signed.
logic CPU_lt_signed_a0;

// For |cpu$lt_unsigned.
logic CPU_lt_unsigned_a0;

// For |cpu$mem_addr.
logic [63:0] CPU_mem_addr_a0;

// For |cpu$mem_byte_off.
logic [2:0] CPU_mem_byte_off_a0;

// For |cpu$mem_bytes_elf.
logic [63:0] CPU_mem_bytes_elf_a0;

// For |cpu$mem_cur_word.
logic [63:0] CPU_mem_cur_word_a0;

// For |cpu$mem_shift_bits.
logic [5:0] CPU_mem_shift_bits_a0;

// For |cpu$mem_shifted.
logic [63:0] CPU_mem_shifted_a0;

// For |cpu$mem_word_idx.
logic [5:0] CPU_mem_word_idx_a0,
            CPU_mem_word_idx_a1;

// For |cpu$op_is_auipc.
logic CPU_op_is_auipc_a0;

// For |cpu$op_is_branch.
logic CPU_op_is_branch_a0;

// For |cpu$op_is_fence.
logic CPU_op_is_fence_a0;

// For |cpu$op_is_imm.
logic CPU_op_is_imm_a0;

// For |cpu$op_is_immw.
logic CPU_op_is_immw_a0;

// For |cpu$op_is_jal.
logic CPU_op_is_jal_a0;

// For |cpu$op_is_jalr.
logic CPU_op_is_jalr_a0;

// For |cpu$op_is_load.
logic CPU_op_is_load_a0;

// For |cpu$op_is_lui.
logic CPU_op_is_lui_a0;

// For |cpu$op_is_reg.
logic CPU_op_is_reg_a0;

// For |cpu$op_is_regw.
logic CPU_op_is_regw_a0;

// For |cpu$op_is_store.
logic CPU_op_is_store_a0;

// For |cpu$opcode.
logic [6:0] CPU_opcode_a0;

// For |cpu$pc.
logic [63:0] CPU_pc_a0,
             CPU_pc_a1;

// For |cpu$pc_src.
logic CPU_pc_src_a0,
      CPU_pc_src_a1;

// For |cpu$rd.
logic [4:0] CPU_rd_a0,
            CPU_rd_a1;

// For |cpu$reg_write.
logic CPU_reg_write_a0,
      CPU_reg_write_a1;

// For |cpu$reset.
logic CPU_reset_a0,
      CPU_reset_a1;

// For |cpu$reset_just_released.
logic CPU_reset_just_released_a0;

// For |cpu$rs1.
logic [4:0] CPU_rs1_a0;

// For |cpu$rs1_data.
logic [63:0] CPU_rs1_data_a0;

// For |cpu$rs2.
logic [4:0] CPU_rs2_a0;

// For |cpu$rs2_data.
logic [63:0] CPU_rs2_data_a0;

// For |cpu$shamt5.
logic [4:0] CPU_shamt5_a0;

// For |cpu$shamt6.
logic [5:0] CPU_shamt6_a0;

// For |cpu$shift_amt32.
logic [4:0] CPU_shift_amt32_a0;

// For |cpu$shift_amt64.
logic [5:0] CPU_shift_amt64_a0;

// For |cpu$sra_ext128.
logic [127:0] CPU_sra_ext128_a0;

// For |cpu$sraw_ext64.
logic [63:0] CPU_sraw_ext64_a0;

// For |cpu$store_data_sh.
logic [63:0] CPU_store_data_sh_a0;

// For |cpu$store_mask.
logic [63:0] CPU_store_mask_a0;

// For |cpu$store_mask_base.
logic [63:0] CPU_store_mask_base_a0;

// For |cpu$wr_data.
logic [63:0] CPU_wr_data_a0,
             CPU_wr_data_a1;

// For |cpu/dmem$val.
logic [63:0] CPU_Dmem_val_a0 [63:0],
             CPU_Dmem_val_a1 [63:0];

// For |cpu/xreg$val.
logic [63:0] CPU_Xreg_val_a0 [31:0],
             CPU_Xreg_val_a1 [31:0];




   //
   // Scope: |cpu
   //

      // Staging of $alt_pc.
      always_ff @(posedge clk) CPU_alt_pc_a1[63:0] <= CPU_alt_pc_a0[63:0];

      // Staging of $cyc_cnt.
      always_ff @(posedge clk) CPU_cyc_cnt_a1[31:0] <= CPU_cyc_cnt_a0[31:0];

      // Staging of $dmem_new_word.
      always_ff @(posedge clk) CPU_dmem_new_word_a1[63:0] <= CPU_dmem_new_word_a0[63:0];

      // Staging of $is_store.
      always_ff @(posedge clk) CPU_is_store_a1 <= CPU_is_store_a0;

      // Staging of $mem_word_idx.
      always_ff @(posedge clk) CPU_mem_word_idx_a1[5:0] <= CPU_mem_word_idx_a0[5:0];

      // Staging of $pc.
      always_ff @(posedge clk) CPU_pc_a1[63:0] <= CPU_pc_a0[63:0];

      // Staging of $pc_src.
      always_ff @(posedge clk) CPU_pc_src_a1 <= CPU_pc_src_a0;

      // Staging of $rd.
      always_ff @(posedge clk) CPU_rd_a1[4:0] <= CPU_rd_a0[4:0];

      // Staging of $reg_write.
      always_ff @(posedge clk) CPU_reg_write_a1 <= CPU_reg_write_a0;

      // Staging of $reset.
      always_ff @(posedge clk) CPU_reset_a1 <= CPU_reset_a0;

      // Staging of $wr_data.
      always_ff @(posedge clk) CPU_wr_data_a1[63:0] <= CPU_wr_data_a0[63:0];


      //
      // Scope: /dmem[63:0]
      //
      for (dmem = 0; dmem <= 63; dmem++) begin : L1gen_CPU_Dmem
         // Staging of $val.
         always_ff @(posedge clk) CPU_Dmem_val_a1[dmem][63:0] <= CPU_Dmem_val_a0[dmem][63:0];

      end

      //
      // Scope: /xreg[31:0]
      //
      for (xreg = 0; xreg <= 31; xreg++) begin : L1gen_CPU_Xreg
         // Staging of $val.
         always_ff @(posedge clk) CPU_Xreg_val_a1[xreg][63:0] <= CPU_Xreg_val_a0[xreg][63:0];

      end


