`line 2 "_novz.tlv" 0 //_\TLV_version 1d: tl-x.org, generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro
`include "sp_m4out.vh" //_\SV
   // ═══════════════════════════════════════════════════════════════════
   //  RVA23 Base Core — RV64I Single-Cycle CPU (Phase 1, Milestone B)
   //  Clean-slate build, not derived from warp-v.tlv. Structural
   //  conventions (encoder-function idiom, /xreg and /dmem array-of-
   //  registers, PASS/FAIL assertion pattern) follow arm_single_cycle.tlv;
   //  all instruction encodings and datapath logic are RV64I-specific.
   //
   //  All 50 RV64I encodings implemented: the 38 RV32I-equivalent
   //  instructions (incl. FENCE, excl. ECALL/EBREAK, deferred) plus the
   //  12 RV64-only *W encodings.
   //
   //  Waveform signals to watch (add in Makerchip waveform panel):
   //    |cpu @0  $pc, $instr, $opcode, $funct3, $funct7, $reg_write,
   //             $alu_result, $branch_taken, $pc_src, $wr_data,
   //             $is_load, $is_store, $mem_addr
   //    /xreg[1..31] $val   — register file values
   //    /dmem[0..63] $val   — data memory (64 doublewords, byte addr 0-511)
   // ═══════════════════════════════════════════════════════════════════
   module top(input wire clk, input wire reset, input wire [31:0] cyc_cnt, output wire passed, output wire failed);    /* verilator lint_save */ /* verilator lint_off UNOPTFLAT */  bit [256:0] RW_rand_raw; bit [256+63:0] RW_rand_vect; pseudo_rand #(.WIDTH(257)) pseudo_rand (clk, reset, RW_rand_raw[256:0]); assign RW_rand_vect[256+63:0] = {RW_rand_raw[62:0], RW_rand_raw};  /* verilator lint_restore */  /* verilator lint_off WIDTH */ /* verilator lint_off UNOPTFLAT */

   // ═══════════════════════════════════════════════════════════════════
   //  INSTRUCTION ENCODER — computes real RV64I 32-bit encodings at
   //  elaboration time. Field layouts verified directly against the
   //  RISC-V ISA manual (R/I/S/B/U/J-type formats, base opcode map,
   //  Zaamo-adjacent shift-immediate conventions for RV64).
   //  Store mnemonics follow real assembly operand order: SB(rs2,rs1,imm)
   //  means "store rs2's value to address rs1+imm" (sb rs2, imm(rs1)).
   // ═══════════════════════════════════════════════════════════════════

   // ── R-type (OP, 0x33) ──
   function automatic logic [31:0] ADD(int rd, int rs1, int rs2);
      return {7'b0000000, rs2[4:0], rs1[4:0], 3'b000, rd[4:0], 7'b0110011};
   endfunction
   function automatic logic [31:0] SUB(int rd, int rs1, int rs2);
      return {7'b0100000, rs2[4:0], rs1[4:0], 3'b000, rd[4:0], 7'b0110011};
   endfunction
   function automatic logic [31:0] SLL(int rd, int rs1, int rs2);
      return {7'b0000000, rs2[4:0], rs1[4:0], 3'b001, rd[4:0], 7'b0110011};
   endfunction
   function automatic logic [31:0] SLT(int rd, int rs1, int rs2);
      return {7'b0000000, rs2[4:0], rs1[4:0], 3'b010, rd[4:0], 7'b0110011};
   endfunction
   function automatic logic [31:0] SLTU(int rd, int rs1, int rs2);
      return {7'b0000000, rs2[4:0], rs1[4:0], 3'b011, rd[4:0], 7'b0110011};
   endfunction
   function automatic logic [31:0] XOR(int rd, int rs1, int rs2);
      return {7'b0000000, rs2[4:0], rs1[4:0], 3'b100, rd[4:0], 7'b0110011};
   endfunction
   function automatic logic [31:0] SRL(int rd, int rs1, int rs2);
      return {7'b0000000, rs2[4:0], rs1[4:0], 3'b101, rd[4:0], 7'b0110011};
   endfunction
   function automatic logic [31:0] SRA(int rd, int rs1, int rs2);
      return {7'b0100000, rs2[4:0], rs1[4:0], 3'b101, rd[4:0], 7'b0110011};
   endfunction
   function automatic logic [31:0] OR(int rd, int rs1, int rs2);
      return {7'b0000000, rs2[4:0], rs1[4:0], 3'b110, rd[4:0], 7'b0110011};
   endfunction
   function automatic logic [31:0] AND(int rd, int rs1, int rs2);
      return {7'b0000000, rs2[4:0], rs1[4:0], 3'b111, rd[4:0], 7'b0110011};
   endfunction

   // ── I-type ALU (OP-IMM, 0x13) ──
   function automatic logic [31:0] ADDI(int rd, int rs1, int imm12);
      return {imm12[11:0], rs1[4:0], 3'b000, rd[4:0], 7'b0010011};
   endfunction
   function automatic logic [31:0] SLTI(int rd, int rs1, int imm12);
      return {imm12[11:0], rs1[4:0], 3'b010, rd[4:0], 7'b0010011};
   endfunction
   function automatic logic [31:0] SLTIU(int rd, int rs1, int imm12);
      return {imm12[11:0], rs1[4:0], 3'b011, rd[4:0], 7'b0010011};
   endfunction
   function automatic logic [31:0] XORI(int rd, int rs1, int imm12);
      return {imm12[11:0], rs1[4:0], 3'b100, rd[4:0], 7'b0010011};
   endfunction
   function automatic logic [31:0] ORI(int rd, int rs1, int imm12);
      return {imm12[11:0], rs1[4:0], 3'b110, rd[4:0], 7'b0010011};
   endfunction
   function automatic logic [31:0] ANDI(int rd, int rs1, int imm12);
      return {imm12[11:0], rs1[4:0], 3'b111, rd[4:0], 7'b0010011};
   endfunction
   // RV64 shift-immediates use a 6-bit shamt (instr[25:20]); instr[31:26]
   // discriminates SLLI/SRLI (000000) from SRAI (010000).
   function automatic logic [31:0] SLLI(int rd, int rs1, int shamt6);
      return {6'b000000, shamt6[5:0], rs1[4:0], 3'b001, rd[4:0], 7'b0010011};
   endfunction
   function automatic logic [31:0] SRLI(int rd, int rs1, int shamt6);
      return {6'b000000, shamt6[5:0], rs1[4:0], 3'b101, rd[4:0], 7'b0010011};
   endfunction
   function automatic logic [31:0] SRAI(int rd, int rs1, int shamt6);
      return {6'b010000, shamt6[5:0], rs1[4:0], 3'b101, rd[4:0], 7'b0010011};
   endfunction

   // ── Branches (BRANCH, 0x63, B-type) ──
   function automatic logic [31:0] BEQ(int rs1, int rs2, int imm13);
      return {imm13[12], imm13[10:5], rs2[4:0], rs1[4:0], 3'b000, imm13[4:1], imm13[11], 7'b1100011};
   endfunction
   function automatic logic [31:0] BNE(int rs1, int rs2, int imm13);
      return {imm13[12], imm13[10:5], rs2[4:0], rs1[4:0], 3'b001, imm13[4:1], imm13[11], 7'b1100011};
   endfunction
   function automatic logic [31:0] BLT(int rs1, int rs2, int imm13);
      return {imm13[12], imm13[10:5], rs2[4:0], rs1[4:0], 3'b100, imm13[4:1], imm13[11], 7'b1100011};
   endfunction
   function automatic logic [31:0] BGE(int rs1, int rs2, int imm13);
      return {imm13[12], imm13[10:5], rs2[4:0], rs1[4:0], 3'b101, imm13[4:1], imm13[11], 7'b1100011};
   endfunction
   function automatic logic [31:0] BLTU(int rs1, int rs2, int imm13);
      return {imm13[12], imm13[10:5], rs2[4:0], rs1[4:0], 3'b110, imm13[4:1], imm13[11], 7'b1100011};
   endfunction
   function automatic logic [31:0] BGEU(int rs1, int rs2, int imm13);
      return {imm13[12], imm13[10:5], rs2[4:0], rs1[4:0], 3'b111, imm13[4:1], imm13[11], 7'b1100011};
   endfunction

   // ── Jumps ──
   function automatic logic [31:0] JAL(int rd, int imm21);
      return {imm21[20], imm21[10:1], imm21[11], imm21[19:12], rd[4:0], 7'b1101111};
   endfunction
   function automatic logic [31:0] JALR(int rd, int rs1, int imm12);
      return {imm12[11:0], rs1[4:0], 3'b000, rd[4:0], 7'b1100111};
   endfunction

   // ── Upper immediate (U-type) ──
   function automatic logic [31:0] LUI(int rd, int imm20);
      return {imm20[19:0], rd[4:0], 7'b0110111};
   endfunction
   function automatic logic [31:0] AUIPC(int rd, int imm20);
      return {imm20[19:0], rd[4:0], 7'b0010111};
   endfunction

   // ── Loads (LOAD, 0x03, I-type) ──
   function automatic logic [31:0] LB(int rd, int rs1, int imm12);
      return {imm12[11:0], rs1[4:0], 3'b000, rd[4:0], 7'b0000011};
   endfunction
   function automatic logic [31:0] LH(int rd, int rs1, int imm12);
      return {imm12[11:0], rs1[4:0], 3'b001, rd[4:0], 7'b0000011};
   endfunction
   function automatic logic [31:0] LW(int rd, int rs1, int imm12);
      return {imm12[11:0], rs1[4:0], 3'b010, rd[4:0], 7'b0000011};
   endfunction
   function automatic logic [31:0] LD(int rd, int rs1, int imm12);
      return {imm12[11:0], rs1[4:0], 3'b011, rd[4:0], 7'b0000011};
   endfunction
   function automatic logic [31:0] LBU(int rd, int rs1, int imm12);
      return {imm12[11:0], rs1[4:0], 3'b100, rd[4:0], 7'b0000011};
   endfunction
   function automatic logic [31:0] LHU(int rd, int rs1, int imm12);
      return {imm12[11:0], rs1[4:0], 3'b101, rd[4:0], 7'b0000011};
   endfunction
   function automatic logic [31:0] LWU(int rd, int rs1, int imm12);
      return {imm12[11:0], rs1[4:0], 3'b110, rd[4:0], 7'b0000011};
   endfunction

   // ── Stores (STORE, 0x23, S-type) ──
   function automatic logic [31:0] SB(int rs2, int rs1, int imm12);
      return {imm12[11:5], rs2[4:0], rs1[4:0], 3'b000, imm12[4:0], 7'b0100011};
   endfunction
   function automatic logic [31:0] SH(int rs2, int rs1, int imm12);
      return {imm12[11:5], rs2[4:0], rs1[4:0], 3'b001, imm12[4:0], 7'b0100011};
   endfunction
   function automatic logic [31:0] SW(int rs2, int rs1, int imm12);
      return {imm12[11:5], rs2[4:0], rs1[4:0], 3'b010, imm12[4:0], 7'b0100011};
   endfunction
   function automatic logic [31:0] SD(int rs2, int rs1, int imm12);
      return {imm12[11:5], rs2[4:0], rs1[4:0], 3'b011, imm12[4:0], 7'b0100011};
   endfunction

   // ── RV64-only *W word ops (OP-IMM-32=0x1B, OP-32=0x3B) ──
   function automatic logic [31:0] ADDIW(int rd, int rs1, int imm12);
      return {imm12[11:0], rs1[4:0], 3'b000, rd[4:0], 7'b0011011};
   endfunction
   // *W shift-immediates use a 5-bit shamt (instr[24:20]); instr[31:25]
   // discriminates SLLIW/SRLIW (0000000) from SRAIW (0100000).
   function automatic logic [31:0] SLLIW(int rd, int rs1, int shamt5);
      return {7'b0000000, shamt5[4:0], rs1[4:0], 3'b001, rd[4:0], 7'b0011011};
   endfunction
   function automatic logic [31:0] SRLIW(int rd, int rs1, int shamt5);
      return {7'b0000000, shamt5[4:0], rs1[4:0], 3'b101, rd[4:0], 7'b0011011};
   endfunction
   function automatic logic [31:0] SRAIW(int rd, int rs1, int shamt5);
      return {7'b0100000, shamt5[4:0], rs1[4:0], 3'b101, rd[4:0], 7'b0011011};
   endfunction
   function automatic logic [31:0] ADDW(int rd, int rs1, int rs2);
      return {7'b0000000, rs2[4:0], rs1[4:0], 3'b000, rd[4:0], 7'b0111011};
   endfunction
   function automatic logic [31:0] SUBW(int rd, int rs1, int rs2);
      return {7'b0100000, rs2[4:0], rs1[4:0], 3'b000, rd[4:0], 7'b0111011};
   endfunction
   function automatic logic [31:0] SLLW(int rd, int rs1, int rs2);
      return {7'b0000000, rs2[4:0], rs1[4:0], 3'b001, rd[4:0], 7'b0111011};
   endfunction
   function automatic logic [31:0] SRLW(int rd, int rs1, int rs2);
      return {7'b0000000, rs2[4:0], rs1[4:0], 3'b101, rd[4:0], 7'b0111011};
   endfunction
   function automatic logic [31:0] SRAW(int rd, int rs1, int rs2);
      return {7'b0100000, rs2[4:0], rs1[4:0], 3'b101, rd[4:0], 7'b0111011};
   endfunction

   // ── FENCE (MISC-MEM, 0x0F) — implemented as a functional NOP (see
   // decode below): no operands needed for that treatment, so pred/succ/
   // fm/rd/rs1 are all just zeroed.
   function automatic logic [31:0] FENCE();
      return {4'b0000, 4'b0000, 4'b0000, 5'b00000, 3'b000, 5'b00000, 7'b0001111};
   endfunction

   // ═══════════════════════════════════════════════════════════════════
   //  THE PROGRAM — hand-assembled, touches all 50 RV64I encodings at
   //  least once. Branch/jump offsets are computed as ROM-index
   //  differences times 4 (byte size), so they are correct by
   //  construction rather than hand-computed hex. Expected values for
   //  every instruction are documented inline for the manual trace
   //  review required by Milestone B's done criteria.
   // ═══════════════════════════════════════════════════════════════════
   localparam int ROM_SIZE = 81;
   logic [31:0] ROM [0:ROM_SIZE-1];
   initial begin
      // ── Phase 1: ALU reg-imm + reg-reg (x1=10, x2=20 held constant
      // throughout the whole program for the branch-comparator tests) ──
      ROM[0]  = ADDI(1, 0, 10);      // x1 = 10
      ROM[1]  = ADDI(2, 0, 20);      // x2 = 20
      ROM[2]  = ADD (3, 1, 2);       // x3 = 30
      ROM[3]  = SUB (4, 2, 1);       // x4 = 10
      ROM[4]  = SLTI (7, 1, 100);    // x7 = 1
      ROM[5]  = SLTIU(8, 1, 100);    // x8 = 1
      ROM[6]  = XORI (9, 1, 15);     // x9 = 5
      ROM[7]  = ORI  (10, 1, 5);     // x10 = 15
      ROM[8]  = ANDI (11, 1, 6);     // x11 = 2
      ROM[9]  = SLLI (12, 1, 2);     // x12 = 40
      ROM[10] = SRLI (13, 12, 2);    // x13 = 10
      ROM[11] = SRAI (14, 12, 2);    // x14 = 10
      ROM[12] = SLL  (15, 1, 11);    // x15 = 40 (10 << x11=2)
      ROM[13] = SLT  (16, 1, 2);     // x16 = 1
      ROM[14] = SLTU (17, 1, 2);     // x17 = 1
      ROM[15] = XOR  (18, 1, 2);     // x18 = 30
      ROM[16] = SRL  (19, 12, 11);   // x19 = 10 (40 >> x11=2)
      ROM[17] = SRA  (20, 12, 11);   // x20 = 10
      ROM[18] = OR   (21, 1, 2);     // x21 = 30
      ROM[19] = AND  (22, 1, 2);     // x22 = 0

      // ── Phase 2: branches, each taken, skipping exactly one decoy
      // (offset = +8 bytes = 2 instructions ahead) ──
      ROM[20] = BNE (1, 2, (22-20)*4);  // 10!=20 taken -> ROM[22]
      ROM[21] = ADDI(23, 0, 999);       // decoy, skipped
      ROM[22] = ADDI(23, 0, 1);         // x23 = 1
      ROM[23] = BLT (1, 2, (25-23)*4);  // 10<20 signed taken -> ROM[25]
      ROM[24] = ADDI(24, 0, 999);       // decoy, skipped
      ROM[25] = ADDI(24, 0, 1);         // x24 = 1 (transient, reused later)
      ROM[26] = BGE (2, 1, (28-26)*4);  // 20>=10 signed taken -> ROM[28]
      ROM[27] = ADDI(25, 0, 999);       // decoy, skipped
      ROM[28] = ADDI(25, 0, 1);         // x25 = 1 (transient, reused later)
      ROM[29] = BLTU(1, 2, (31-29)*4);  // 10<20 unsigned taken -> ROM[31]
      ROM[30] = ADDI(26, 0, 999);       // decoy, skipped
      ROM[31] = ADDI(26, 0, 1);         // x26 = 1 (transient, reused later)
      ROM[32] = BGEU(2, 1, (34-32)*4);  // 20>=10 unsigned taken -> ROM[34]
      ROM[33] = ADDI(27, 0, 999);       // decoy, skipped
      ROM[34] = ADDI(27, 0, 1);         // x27 = 1 (transient, reused later)
      ROM[35] = BEQ (1, 1, (37-35)*4);  // 10==10 taken -> ROM[37]
      ROM[36] = ADDI(28, 0, 999);       // decoy, skipped (x28 stays 0)

      // ── Phase 3: JAL (link register + forward jump) ──
      ROM[37] = JAL (29, (39-37)*4);    // x29 = link = addr(37)+4 = 152; -> ROM[39]
      ROM[38] = ADDI(29, 0, 999);       // decoy, skipped (JAL always taken)
      ROM[39] = ADDI(30, 0, 1);         // x30 = 1 (JAL landing confirmed)

      // ── Phase 4: LUI / AUIPC ──
      ROM[40] = AUIPC(7, 0);            // x7 = pc(this instr) = 160 -- verify against trace's own pc column
      ROM[41] = LUI  (8, 1);            // x8 = 0x1000 = 4096
      ROM[42] = ADDI (9, 0, 64);        // x9 = 64 (memory test base address)

      // ── Phase 5: load/store byte-lane round trips ──
      ROM[43] = ADDI(10, 0, -1);        // x10 = -1 (all-ones, 0xFFFF...FFFF)
      ROM[44] = SD  (10, 9, 0);         // mem[64] (doubleword) = all-ones
      ROM[45] = LD  (11, 9, 0);         // x11 = -1 (full doubleword round trip)
      ROM[46] = ADDI(12, 0, 2047);      // x12 = 2047 (0x7FF)
      ROM[47] = SW  (12, 9, 8);         // mem word @72 = 2047
      ROM[48] = LW  (13, 9, 8);         // x13 = 2047 (sign-extend path, positive)
      ROM[49] = LWU (14, 9, 8);         // x14 = 2047 (zero-extend path)
      ROM[50] = ADDI(15, 0, -100);      // x15 = -100 (transient, reused later)
      ROM[51] = SH  (15, 9, 16);        // mem halfword @80 = 0xFF9C
      ROM[52] = LH  (16, 9, 16);        // x16 = -100 (sign-extend path)
      ROM[53] = LHU (17, 9, 16);        // x17 = 65436 (zero-extend path, =0xFF9C unsigned)
      ROM[54] = ADDI(18, 0, -5);        // x18 = -5
      ROM[55] = SB  (18, 9, 24);        // mem byte @88 = 0xFB
      ROM[56] = LB  (19, 9, 24);        // x19 = -5 (sign-extend path)
      ROM[57] = LBU (20, 9, 24);        // x20 = 251 (zero-extend path)
      // Unaligned, same-doubleword-different-byte-lane round trip: byte
      // @91 shares word_idx=11 with byte @88 (written above at offset 0
      // within that word) but at byte_off=3 -- proves byte-lane write
      // masking updates only its own lane without clobbering byte 0.
      ROM[58] = ADDI(21, 0, 42);        // x21 = 42
      ROM[59] = SB  (21, 9, 27);        // mem byte @91 (same word as @88, byte_off 3) = 42
      ROM[60] = LB  (22, 9, 27);        // x22 = 42 (readback of the just-written byte)
      ROM[61] = LB  (31, 9, 24);        // x31 = -5 again (re-check byte @88/byte_off 0 unclobbered)

      // ── Phase 6: RV64-only *W ops. x24 = 0x80000000 (2^31) is the key
      // operand: as a *W (32-bit) op, adding 1 to it overflows the 32-bit
      // sign bit, giving a large NEGATIVE 64-bit result after sign
      // extension -- dramatically different from a plain 64-bit ADD on
      // the same bit pattern, which stays a small POSITIVE number. This
      // is the required spot-check proving *W truncate+sign-extend is
      // real and distinct from the non-W path. ──
      ROM[62] = ADDI(24, 0, 1);
      ROM[63] = SLLI(24, 24, 31);       // x24 = 1<<31 = 0x0000000080000000 (2147483648)
      ROM[64] = ADDI(25, 0, 1);         // x25 = 1
      ROM[65] = ADDW(26, 24, 25);       // x26 = sign-extend32(0x80000001) = -2147483647
      ROM[66] = ADD (27, 24, 25);       // x27 = 0x0000000080000001 = +2147483649 (DIFFERS from x26)
      ROM[67] = SUBW(28, 25, 24);       // x28 = sign-extend32(1-0x80000000 mod 2^32) = -2147483647 (cross-check vs x26)
      ROM[68] = SLLIW(5, 25, 31);       // x5 = sign-extend32(1<<31 truncated) = -2147483648 (INT32_MIN)
      ROM[69] = SRLIW(6, 24, 4);        // x24[31:0]=0x80000000 >>logical 4 = 0x08000000, sign-extend positive = 134217728
      ROM[70] = SRAIW(8, 24, 4);        // x24[31:0]=0x80000000 >>arith 4 = 0xF8000000, sign-extend negative = -134217728
      ROM[71] = ADDIW(9, 24, 1);        // x24[31:0]+1 = 0x80000001, sign-extend = -2147483647 (matches x26/x28)
      ROM[72] = SLLW(10, 1, 25);        // x1=10, shift by x25[4:0]=1 -> 20 (32-bit, sign-extend positive)
      ROM[73] = SRLW(11, 24, 25);       // x24[31:0]=0x80000000 >>logical 1 = 0x40000000, sign-extend positive = 1073741824
      ROM[74] = SRAW(12, 24, 25);       // x24[31:0]=0x80000000 >>arith 1 = 0xC0000000, sign-extend negative = -1073741824

      // ── Phase 7: JALR (rs1=x0, so target = imm12 directly = an
      // absolute address -- valid since the whole program fits well
      // within the +-2047 range of a 12-bit signed immediate) ──
      ROM[75] = JALR(13, 0, 77*4);      // x13 = link = addr(75)+4 = 304; jump to ROM[77]
      ROM[76] = ADDI(14, 0, 999);       // decoy, skipped
      ROM[77] = ADDI(15, 0, 1);         // x15 = 1 (JALR landing confirmed)

      // ── Phase 8: FENCE (functional NOP) ──
      ROM[78] = FENCE();
      ROM[79] = ADDI(16, 0, 1);         // x16 = 1 (confirms execution continued normally past FENCE)

      // ── Final: jump to self, freezes state for the PASS assertion ──
      ROM[80] = JAL(0, 0);
   end

   // ═══════════════════════════════════════════════════════════════════
   //  MILESTONE C: ACT4 ELF-loaded memory. A real ACT4 test ELF places
   //  code, data, signature region, and tohost/fromhost all in one
   //  unified 0x80000000-based address space (confirmed via readelf on
   //  a real generated ELF: .text.init@0x80000000, .data@0x8000c000,
   //  .tohost shifting per-test e.g. 0x80037920/0x80025310/0x8003a6f0
   //  depending on each test's own signature-table size). This is
   //  structurally different from the small, hand-assembled, Harvard-
   //  style ROM[]/dmem[] used above for Milestones A/B, so it is added
   //  as a parallel, independently-selected memory rather than altering
   //  that already-verified path. Sized 512KiB (0x80000), comfortably
   //  covering real ELF footprints observed (~208KiB for I-add-00).
   //  The array's own index range is declared to match real ELF byte
   //  addresses directly (0x80000000..0x8007FFFF) so objcopy -O verilog
   //  output -- confirmed empirically to emit byte-level data with
   //  absolute-address @-annotations -- loads via $readmemh with no
   //  address translation needed in the datapath logic below.
   // ═══════════════════════════════════════════════════════════════════
   localparam bit [31:0] ELFMEM_BASE = 32'h8000_0000;
   localparam bit [31:0] ELFMEM_SIZE = 32'h0008_0000;
   logic [7:0] elfmem [ELFMEM_BASE : ELFMEM_BASE + ELFMEM_SIZE - 1];
   logic act4_mode;
   initial begin
      string elf_hex_path;
      act4_mode = 1'b0;
      if ($value$plusargs("elf_hex=%s", elf_hex_path)) begin
         $readmemh(elf_hex_path, elfmem);
         act4_mode = 1'b1;
      end
   end

`include "rv64i_core_gen.sv" //_\TLV

   //_|cpu
      //_@0
         // ─────────────────────────────────────────────────────────
         //  RESET
         // ─────────────────────────────────────────────────────────
         assign CPU_reset_a0 = reset;

         // ─────────────────────────────────────────────────────────
         //  CYCLE COUNTER
         // ─────────────────────────────────────────────────────────
         assign CPU_cyc_cnt_a0[31:0] = CPU_reset_a0 ? 32'b0 : CPU_cyc_cnt_a1 + 32'd1;

         // ─────────────────────────────────────────────────────────
         //  PROGRAM COUNTER — same one-extra-cycle-after-reset handling
         //  as Milestone A / arm_single_cycle.tlv.
         // ─────────────────────────────────────────────────────────
         assign CPU_reset_just_released_a0 = CPU_reset_a1 && !CPU_reset_a0;
         assign CPU_pc_a0[63:0] =
            (CPU_reset_a0 || CPU_reset_just_released_a0) ? (act4_mode ? {32'b0, ELFMEM_BASE} : 64'b0) :
            CPU_pc_src_a1                       ? CPU_alt_pc_a1 :
                                                CPU_pc_a1 + 64'd4;

         // ─────────────────────────────────────────────────────────
         //  INSTRUCTION MEMORY — Milestone A/B hand-assembled ROM[]
         //  (pc[8:2] gives a 7-bit index, 0-127, byte addresses 0-508,
         //  comfortably covering ROM_SIZE=81), or Milestone C's
         //  ELF-loaded elfmem[] (little-endian 4-byte read at $pc, real
         //  absolute address), selected by act4_mode.
         // ─────────────────────────────────────────────────────────
         assign CPU_instr_rom_a0[31:0]  = ROM[(CPU_pc_a0[8:2] >= ROM_SIZE) ? ROM_SIZE - 1 : CPU_pc_a0[8:2]];
         assign CPU_instr_elf_a0[31:0]  = {elfmem[CPU_pc_a0[31:0]+3], elfmem[CPU_pc_a0[31:0]+2], elfmem[CPU_pc_a0[31:0]+1], elfmem[CPU_pc_a0[31:0]+0]};
         assign CPU_instr_a0[31:0] = act4_mode ? CPU_instr_elf_a0 : CPU_instr_rom_a0;

         // ─────────────────────────────────────────────────────────
         //  DECODE
         // ─────────────────────────────────────────────────────────
         assign CPU_opcode_a0[6:0] = CPU_instr_a0[6:0];
         assign CPU_funct3_a0[2:0] = CPU_instr_a0[14:12];
         assign CPU_funct7_a0[6:0] = CPU_instr_a0[31:25];
         // RV64I's 6-bit-shamt SLLI/SRLI/SRAI use instr[25:20] as a
         // 6-bit shamt (needed to encode shifts up to 63) -- meaning
         // bit 25 is part of the *shamt*, not the opcode discriminator,
         // for these three instructions specifically. The real
         // discriminator is funct6 = instr[31:26] (6 bits: 000000 for
         // SLLI/SRLI, 010000 for SRAI), verified against the RISC-V ISA
         // manual's own RV64I shift-immediate encoding. Using the full
         // 7-bit $funct7 (as the *W shift-immediates correctly do, since
         // those only need a 5-bit shamt and bit 25 is genuinely part of
         // their discriminator) would misdecode any SLLI/SRLI/SRAI whose
         // shift amount is >=32 as an unrecognized instruction, since
         // bit 25 (shamt[5]) would then be 1, not matching funct7==0.
         assign CPU_funct6_a0[5:0] = CPU_instr_a0[31:26];
         assign CPU_rd_a0[4:0]     = CPU_instr_a0[11:7];
         assign CPU_rs1_a0[4:0]    = CPU_instr_a0[19:15];
         assign CPU_rs2_a0[4:0]    = CPU_instr_a0[24:20];
         assign CPU_shamt6_a0[5:0] = CPU_instr_a0[25:20];
         assign CPU_shamt5_a0[4:0] = CPU_instr_a0[24:20];

         assign CPU_op_is_load_a0   = (CPU_opcode_a0 == 7'b0000011);
         assign CPU_op_is_imm_a0    = (CPU_opcode_a0 == 7'b0010011);
         assign CPU_op_is_auipc_a0  = (CPU_opcode_a0 == 7'b0010111);
         assign CPU_op_is_store_a0  = (CPU_opcode_a0 == 7'b0100011);
         assign CPU_op_is_reg_a0    = (CPU_opcode_a0 == 7'b0110011);
         assign CPU_op_is_lui_a0    = (CPU_opcode_a0 == 7'b0110111);
         assign CPU_op_is_branch_a0 = (CPU_opcode_a0 == 7'b1100011);
         assign CPU_op_is_jalr_a0   = (CPU_opcode_a0 == 7'b1100111);
         assign CPU_op_is_jal_a0    = (CPU_opcode_a0 == 7'b1101111);
         assign CPU_op_is_immw_a0   = (CPU_opcode_a0 == 7'b0011011);
         assign CPU_op_is_regw_a0   = (CPU_opcode_a0 == 7'b0111011);
         assign CPU_op_is_fence_a0  = (CPU_opcode_a0 == 7'b0001111);

         assign CPU_is_lb_a0  = CPU_op_is_load_a0 && (CPU_funct3_a0 == 3'b000);
         assign CPU_is_lh_a0  = CPU_op_is_load_a0 && (CPU_funct3_a0 == 3'b001);
         assign CPU_is_lw_a0  = CPU_op_is_load_a0 && (CPU_funct3_a0 == 3'b010);
         assign CPU_is_ld_a0  = CPU_op_is_load_a0 && (CPU_funct3_a0 == 3'b011);
         assign CPU_is_lbu_a0 = CPU_op_is_load_a0 && (CPU_funct3_a0 == 3'b100);
         assign CPU_is_lhu_a0 = CPU_op_is_load_a0 && (CPU_funct3_a0 == 3'b101);
         assign CPU_is_lwu_a0 = CPU_op_is_load_a0 && (CPU_funct3_a0 == 3'b110);
         assign CPU_is_load_a0 = CPU_op_is_load_a0;

         assign CPU_is_addi_a0  = CPU_op_is_imm_a0 && (CPU_funct3_a0 == 3'b000);
         assign CPU_is_slti_a0  = CPU_op_is_imm_a0 && (CPU_funct3_a0 == 3'b010);
         assign CPU_is_sltiu_a0 = CPU_op_is_imm_a0 && (CPU_funct3_a0 == 3'b011);
         assign CPU_is_xori_a0  = CPU_op_is_imm_a0 && (CPU_funct3_a0 == 3'b100);
         assign CPU_is_ori_a0   = CPU_op_is_imm_a0 && (CPU_funct3_a0 == 3'b110);
         assign CPU_is_andi_a0  = CPU_op_is_imm_a0 && (CPU_funct3_a0 == 3'b111);
         assign CPU_is_slli_a0  = CPU_op_is_imm_a0 && (CPU_funct3_a0 == 3'b001) && (CPU_funct6_a0 == 6'b000000);
         assign CPU_is_srli_a0  = CPU_op_is_imm_a0 && (CPU_funct3_a0 == 3'b101) && (CPU_funct6_a0 == 6'b000000);
         assign CPU_is_srai_a0  = CPU_op_is_imm_a0 && (CPU_funct3_a0 == 3'b101) && (CPU_funct6_a0 == 6'b010000);

         assign CPU_is_auipc_a0 = CPU_op_is_auipc_a0;

         assign CPU_is_sb_a0 = CPU_op_is_store_a0 && (CPU_funct3_a0 == 3'b000);
         assign CPU_is_sh_a0 = CPU_op_is_store_a0 && (CPU_funct3_a0 == 3'b001);
         assign CPU_is_sw_a0 = CPU_op_is_store_a0 && (CPU_funct3_a0 == 3'b010);
         assign CPU_is_sd_a0 = CPU_op_is_store_a0 && (CPU_funct3_a0 == 3'b011);
         assign CPU_is_store_a0 = CPU_op_is_store_a0;

         assign CPU_is_add_a0  = CPU_op_is_reg_a0 && (CPU_funct3_a0 == 3'b000) && (CPU_funct7_a0 == 7'b0000000);
         assign CPU_is_sub_a0  = CPU_op_is_reg_a0 && (CPU_funct3_a0 == 3'b000) && (CPU_funct7_a0 == 7'b0100000);
         assign CPU_is_sll_a0  = CPU_op_is_reg_a0 && (CPU_funct3_a0 == 3'b001) && (CPU_funct7_a0 == 7'b0000000);
         assign CPU_is_slt_a0  = CPU_op_is_reg_a0 && (CPU_funct3_a0 == 3'b010) && (CPU_funct7_a0 == 7'b0000000);
         assign CPU_is_sltu_a0 = CPU_op_is_reg_a0 && (CPU_funct3_a0 == 3'b011) && (CPU_funct7_a0 == 7'b0000000);
         assign CPU_is_xor_a0  = CPU_op_is_reg_a0 && (CPU_funct3_a0 == 3'b100) && (CPU_funct7_a0 == 7'b0000000);
         assign CPU_is_srl_a0  = CPU_op_is_reg_a0 && (CPU_funct3_a0 == 3'b101) && (CPU_funct7_a0 == 7'b0000000);
         assign CPU_is_sra_a0  = CPU_op_is_reg_a0 && (CPU_funct3_a0 == 3'b101) && (CPU_funct7_a0 == 7'b0100000);
         assign CPU_is_or_a0   = CPU_op_is_reg_a0 && (CPU_funct3_a0 == 3'b110) && (CPU_funct7_a0 == 7'b0000000);
         assign CPU_is_and_a0  = CPU_op_is_reg_a0 && (CPU_funct3_a0 == 3'b111) && (CPU_funct7_a0 == 7'b0000000);

         assign CPU_is_lui_a0 = CPU_op_is_lui_a0;

         assign CPU_is_beq_a0  = CPU_op_is_branch_a0 && (CPU_funct3_a0 == 3'b000);
         assign CPU_is_bne_a0  = CPU_op_is_branch_a0 && (CPU_funct3_a0 == 3'b001);
         assign CPU_is_blt_a0  = CPU_op_is_branch_a0 && (CPU_funct3_a0 == 3'b100);
         assign CPU_is_bge_a0  = CPU_op_is_branch_a0 && (CPU_funct3_a0 == 3'b101);
         assign CPU_is_bltu_a0 = CPU_op_is_branch_a0 && (CPU_funct3_a0 == 3'b110);
         assign CPU_is_bgeu_a0 = CPU_op_is_branch_a0 && (CPU_funct3_a0 == 3'b111);

         assign CPU_is_jalr_a0 = CPU_op_is_jalr_a0;
         assign CPU_is_jal_a0  = CPU_op_is_jal_a0;

         assign CPU_is_addiw_a0 = CPU_op_is_immw_a0 && (CPU_funct3_a0 == 3'b000);
         assign CPU_is_slliw_a0 = CPU_op_is_immw_a0 && (CPU_funct3_a0 == 3'b001) && (CPU_funct7_a0 == 7'b0000000);
         assign CPU_is_srliw_a0 = CPU_op_is_immw_a0 && (CPU_funct3_a0 == 3'b101) && (CPU_funct7_a0 == 7'b0000000);
         assign CPU_is_sraiw_a0 = CPU_op_is_immw_a0 && (CPU_funct3_a0 == 3'b101) && (CPU_funct7_a0 == 7'b0100000);

         assign CPU_is_addw_a0 = CPU_op_is_regw_a0 && (CPU_funct3_a0 == 3'b000) && (CPU_funct7_a0 == 7'b0000000);
         assign CPU_is_subw_a0 = CPU_op_is_regw_a0 && (CPU_funct3_a0 == 3'b000) && (CPU_funct7_a0 == 7'b0100000);
         assign CPU_is_sllw_a0 = CPU_op_is_regw_a0 && (CPU_funct3_a0 == 3'b001) && (CPU_funct7_a0 == 7'b0000000);
         assign CPU_is_srlw_a0 = CPU_op_is_regw_a0 && (CPU_funct3_a0 == 3'b101) && (CPU_funct7_a0 == 7'b0000000);
         assign CPU_is_sraw_a0 = CPU_op_is_regw_a0 && (CPU_funct3_a0 == 3'b101) && (CPU_funct7_a0 == 7'b0100000);

         assign CPU_is_fence_a0 = CPU_op_is_fence_a0;
         // Decoded but intentionally unused this phase (FENCE is a
         // functional NOP -- no memory-ordering hazards exist in a
         // single-cycle, single-hart core); silences the SandPiper
         // unused-signal warning per the tool's own suggested idiom.
         `BOGUS_USE(CPU_is_fence_a0)

         assign CPU_is_shift_imm_a0  = CPU_is_slli_a0 || CPU_is_srli_a0 || CPU_is_srai_a0;
         assign CPU_is_shift_immw_a0 = CPU_is_slliw_a0 || CPU_is_srliw_a0 || CPU_is_sraiw_a0;
         assign CPU_is_alu_imm_a0    = CPU_is_addi_a0 || CPU_is_slti_a0 || CPU_is_sltiu_a0 || CPU_is_xori_a0 || CPU_is_ori_a0 || CPU_is_andi_a0 || CPU_is_shift_imm_a0;
         assign CPU_is_alu_reg_a0    = CPU_is_add_a0 || CPU_is_sub_a0 || CPU_is_sll_a0 || CPU_is_slt_a0 || CPU_is_sltu_a0 || CPU_is_xor_a0 || CPU_is_srl_a0 || CPU_is_sra_a0 || CPU_is_or_a0 || CPU_is_and_a0;
         assign CPU_is_alu_immw_a0   = CPU_is_addiw_a0 || CPU_is_shift_immw_a0;
         assign CPU_is_alu_regw_a0   = CPU_is_addw_a0 || CPU_is_subw_a0 || CPU_is_sllw_a0 || CPU_is_srlw_a0 || CPU_is_sraw_a0;
         assign CPU_is_w_op_a0       = CPU_is_alu_immw_a0 || CPU_is_alu_regw_a0;

         assign CPU_reg_write_a0 = CPU_is_load_a0 || CPU_is_alu_imm_a0 || CPU_is_alu_reg_a0 || CPU_is_lui_a0 || CPU_is_auipc_a0 ||
                      CPU_is_jal_a0 || CPU_is_jalr_a0 || CPU_is_alu_immw_a0 || CPU_is_alu_regw_a0;

         // ─────────────────────────────────────────────────────────
         //  REGISTER FILE (32 x 64-bit), x0 hardwired to 0
         // ─────────────────────────────────────────────────────────
         for (xreg = 0; xreg <= 31; xreg++) begin : L1_CPU_Xreg logic L1_wr_en_a0; //_/xreg
            assign L1_wr_en_a0 = CPU_reg_write_a1 &&
                     (CPU_rd_a1 == xreg) &&
                     (xreg != 5'b0);
            assign CPU_Xreg_val_a0[xreg][63:0] = (CPU_reset_a0 || CPU_reset_a1) ? 64'b0 :
                         L1_wr_en_a0 ? CPU_wr_data_a1 :
                                  CPU_Xreg_val_a1[xreg][63:0]; end
         assign CPU_rs1_data_a0[63:0] = (CPU_rs1_a0 == 5'd0) ? 64'b0 : CPU_Xreg_val_a0[CPU_rs1_a0];
         assign CPU_rs2_data_a0[63:0] = (CPU_rs2_a0 == 5'd0) ? 64'b0 : CPU_Xreg_val_a0[CPU_rs2_a0];

         // ─────────────────────────────────────────────────────────
         //  IMMEDIATE GENERATION — bit layouts verified against the
         //  RISC-V ISA manual's own immediate-encoding figures.
         // ─────────────────────────────────────────────────────────
         assign CPU_imm_i_a0[63:0] = {{52{CPU_instr_a0[31]}}, CPU_instr_a0[31:20]};
         assign CPU_imm_s_a0[63:0] = {{52{CPU_instr_a0[31]}}, CPU_instr_a0[31:25], CPU_instr_a0[11:7]};
         assign CPU_imm_b_a0[63:0] = {{51{CPU_instr_a0[31]}}, CPU_instr_a0[31], CPU_instr_a0[7], CPU_instr_a0[30:25], CPU_instr_a0[11:8], 1'b0};
         assign CPU_imm_u_a0[63:0] = {{32{CPU_instr_a0[31]}}, CPU_instr_a0[31:12], 12'b0};
         assign CPU_imm_j_a0[63:0] = {{43{CPU_instr_a0[31]}}, CPU_instr_a0[31], CPU_instr_a0[19:12], CPU_instr_a0[20], CPU_instr_a0[30:21], 1'b0};

         // ─────────────────────────────────────────────────────────
         //  ALU — full 64-bit op table plus the 32-bit *W path
         //  (compute on the low 32 bits, then sign-extend to 64).
         // ─────────────────────────────────────────────────────────
         assign CPU_alu_op2_a0[63:0]     = (CPU_is_alu_reg_a0 || CPU_is_alu_regw_a0) ? CPU_rs2_data_a0 : CPU_imm_i_a0;
         assign CPU_shift_amt64_a0[5:0]  = (CPU_is_sll_a0 || CPU_is_srl_a0 || CPU_is_sra_a0) ? CPU_rs2_data_a0[5:0] : CPU_shamt6_a0;
         assign CPU_shift_amt32_a0[4:0]  = (CPU_is_sllw_a0 || CPU_is_srlw_a0 || CPU_is_sraw_a0) ? CPU_rs2_data_a0[4:0] : CPU_shamt5_a0;
         // Signed less-than without a `signed` cast (the `$` sigil in
         // "$signed(...)" collides with TL-Verilog's own signal-name
         // syntax and is misparsed as a signal reference): if the sign
         // bits differ, the operand whose sign bit is set is the smaller
         // one; otherwise a plain unsigned compare already gives the
         // correct signed result.
         assign CPU_lt_signed_a0         = (CPU_rs1_data_a0[63] != CPU_alu_op2_a0[63]) ? CPU_rs1_data_a0[63] : (CPU_rs1_data_a0 < CPU_alu_op2_a0);
         assign CPU_lt_unsigned_a0       = (CPU_rs1_data_a0 < CPU_alu_op2_a0);
         // Arithmetic right shift built from sign-bit replication +
         // logical shift, for the same reason (no `$signed()` cast):
         // concatenate the sign bit ahead of the value, logical-shift
         // the widened value, then take the low bits.
         assign CPU_sra_ext128_a0[127:0]  = {{64{CPU_rs1_data_a0[63]}}, CPU_rs1_data_a0};
         assign CPU_alu_sra64_a0[63:0]    = (CPU_sra_ext128_a0 >> CPU_shift_amt64_a0);
         assign CPU_sraw_ext64_a0[63:0]   = {{32{CPU_rs1_data_a0[31]}}, CPU_rs1_data_a0[31:0]};
         assign CPU_alu_sraw32_wide_a0[63:0] = (CPU_sraw_ext64_a0 >> CPU_shift_amt32_a0);

         assign CPU_alu_result64_a0[63:0] =
            (CPU_is_add_a0 || CPU_is_addi_a0)   ? (CPU_rs1_data_a0 + CPU_alu_op2_a0) :
            CPU_is_sub_a0                  ? (CPU_rs1_data_a0 - CPU_rs2_data_a0) :
            (CPU_is_sll_a0 || CPU_is_slli_a0)    ? (CPU_rs1_data_a0 << CPU_shift_amt64_a0) :
            (CPU_is_slt_a0 || CPU_is_slti_a0)    ? {63'b0, CPU_lt_signed_a0} :
            (CPU_is_sltu_a0 || CPU_is_sltiu_a0)  ? {63'b0, CPU_lt_unsigned_a0} :
            (CPU_is_xor_a0 || CPU_is_xori_a0)    ? (CPU_rs1_data_a0 ^ CPU_alu_op2_a0) :
            (CPU_is_srl_a0 || CPU_is_srli_a0)    ? (CPU_rs1_data_a0 >> CPU_shift_amt64_a0) :
            (CPU_is_sra_a0 || CPU_is_srai_a0)    ? CPU_alu_sra64_a0 :
            (CPU_is_or_a0 || CPU_is_ori_a0)      ? (CPU_rs1_data_a0 | CPU_alu_op2_a0) :
            (CPU_is_and_a0 || CPU_is_andi_a0)    ? (CPU_rs1_data_a0 & CPU_alu_op2_a0) :
                                        64'b0;

         assign CPU_alu_result32_raw_a0[31:0] =
            (CPU_is_addw_a0 || CPU_is_addiw_a0)              ? (CPU_rs1_data_a0[31:0] + CPU_alu_op2_a0[31:0]) :
            CPU_is_subw_a0                               ? (CPU_rs1_data_a0[31:0] - CPU_rs2_data_a0[31:0]) :
            (CPU_is_sllw_a0 || CPU_is_slliw_a0)                ? (CPU_rs1_data_a0[31:0] << CPU_shift_amt32_a0) :
            (CPU_is_srlw_a0 || CPU_is_srliw_a0)                ? (CPU_rs1_data_a0[31:0] >> CPU_shift_amt32_a0) :
            (CPU_is_sraw_a0 || CPU_is_sraiw_a0)                ? CPU_alu_sraw32_wide_a0[31:0] :
                                                       32'b0;
         assign CPU_alu_result32_a0[63:0] = {{32{CPU_alu_result32_raw_a0[31]}}, CPU_alu_result32_raw_a0};

         assign CPU_alu_result_a0[63:0] = CPU_is_w_op_a0 ? CPU_alu_result32_a0 : CPU_alu_result64_a0;

         // ─────────────────────────────────────────────────────────
         //  BRANCH / JUMP TARGET
         // ─────────────────────────────────────────────────────────
         // Same sign-bit-based technique as $lt_signed above (no
         // $signed() cast, for the same TL-Verilog $-sigil reason).
         assign CPU_blt_signed_a0 = (CPU_rs1_data_a0[63] != CPU_rs2_data_a0[63]) ? CPU_rs1_data_a0[63] : (CPU_rs1_data_a0 < CPU_rs2_data_a0);
         assign CPU_branch_taken_a0 =
            (CPU_is_beq_a0  && (CPU_rs1_data_a0 == CPU_rs2_data_a0)) ||
            (CPU_is_bne_a0  && (CPU_rs1_data_a0 != CPU_rs2_data_a0)) ||
            (CPU_is_blt_a0  && CPU_blt_signed_a0) ||
            (CPU_is_bge_a0  && !CPU_blt_signed_a0) ||
            (CPU_is_bltu_a0 && (CPU_rs1_data_a0 < CPU_rs2_data_a0)) ||
            (CPU_is_bgeu_a0 && (CPU_rs1_data_a0 >= CPU_rs2_data_a0));
         assign CPU_branch_target_a0[63:0] = CPU_pc_a0 + CPU_imm_b_a0;
         assign CPU_jal_target_a0[63:0]    = CPU_pc_a0 + CPU_imm_j_a0;
         assign CPU_jalr_target_a0[63:0]   = (CPU_rs1_data_a0 + CPU_imm_i_a0) & ~64'b1;
         assign CPU_pc_src_a0 = CPU_is_jal_a0 || CPU_is_jalr_a0 || CPU_branch_taken_a0;
         assign CPU_alt_pc_a0[63:0] = CPU_is_jal_a0 ? CPU_jal_target_a0 : CPU_is_jalr_a0 ? CPU_jalr_target_a0 : CPU_branch_target_a0;

         // ─────────────────────────────────────────────────────────
         //  DATA MEMORY — byte-addressable via a doubleword-granular
         //  /dmem array (64 entries, byte addresses 0-511) with
         //  explicit byte-lane shift/mask/merge logic on top, the
         //  standard technique for byte-addressable memory backed by
         //  word-granular storage.
         // ─────────────────────────────────────────────────────────
         assign CPU_mem_addr_a0[63:0]     = CPU_rs1_data_a0 + (CPU_is_store_a0 ? CPU_imm_s_a0 : CPU_imm_i_a0);
         assign CPU_mem_word_idx_a0[5:0]  = CPU_mem_addr_a0[8:3];
         assign CPU_mem_byte_off_a0[2:0]  = CPU_mem_addr_a0[2:0];
         assign CPU_mem_shift_bits_a0[5:0] = {CPU_mem_byte_off_a0, 3'b0};

         assign CPU_mem_cur_word_a0[63:0] = CPU_Dmem_val_a0[CPU_mem_word_idx_a0];
         // Milestone C: an 8-byte little-endian read starting at the
         // exact target address, straight from elfmem -- equivalent in
         // shape to $mem_cur_word already shifted so the target byte
         // sits at bit 0, so it slots into the *existing* width-based
         // extraction/sign-extension logic below completely unchanged.
         assign CPU_mem_bytes_elf_a0[63:0] =
            {elfmem[CPU_mem_addr_a0[31:0]+7], elfmem[CPU_mem_addr_a0[31:0]+6],
             elfmem[CPU_mem_addr_a0[31:0]+5], elfmem[CPU_mem_addr_a0[31:0]+4],
             elfmem[CPU_mem_addr_a0[31:0]+3], elfmem[CPU_mem_addr_a0[31:0]+2],
             elfmem[CPU_mem_addr_a0[31:0]+1], elfmem[CPU_mem_addr_a0[31:0]+0]};
         assign CPU_mem_shifted_a0[63:0]  = act4_mode ? CPU_mem_bytes_elf_a0 : (CPU_mem_cur_word_a0 >> CPU_mem_shift_bits_a0);

         assign CPU_load_data_a0[63:0] =
            CPU_is_lb_a0  ? {{56{CPU_mem_shifted_a0[7]}},  CPU_mem_shifted_a0[7:0]}  :
            CPU_is_lh_a0  ? {{48{CPU_mem_shifted_a0[15]}}, CPU_mem_shifted_a0[15:0]} :
            CPU_is_lw_a0  ? {{32{CPU_mem_shifted_a0[31]}}, CPU_mem_shifted_a0[31:0]} :
            CPU_is_lbu_a0 ? {56'b0, CPU_mem_shifted_a0[7:0]}  :
            CPU_is_lhu_a0 ? {48'b0, CPU_mem_shifted_a0[15:0]} :
            CPU_is_lwu_a0 ? {32'b0, CPU_mem_shifted_a0[31:0]} :
            CPU_is_ld_a0  ? CPU_mem_shifted_a0 :
                      64'b0;

         assign CPU_store_mask_base_a0[63:0] =
            CPU_is_sb_a0 ? 64'h00000000000000FF :
            CPU_is_sh_a0 ? 64'h000000000000FFFF :
            CPU_is_sw_a0 ? 64'h00000000FFFFFFFF :
            CPU_is_sd_a0 ? 64'hFFFFFFFFFFFFFFFF :
                     64'b0;
         assign CPU_store_mask_a0[63:0]     = CPU_store_mask_base_a0 << CPU_mem_shift_bits_a0;
         assign CPU_store_data_sh_a0[63:0]  = (CPU_rs2_data_a0 << CPU_mem_shift_bits_a0) & CPU_store_mask_a0;
         assign CPU_dmem_new_word_a0[63:0]  = (CPU_mem_cur_word_a0 & ~CPU_store_mask_a0) | CPU_store_data_sh_a0;

         for (dmem = 0; dmem <= 63; dmem++) begin : L1_CPU_Dmem logic L1_wr_en_a0; //_/dmem
            assign L1_wr_en_a0 = CPU_is_store_a1 &&
                     (CPU_mem_word_idx_a1 == dmem);
            assign CPU_Dmem_val_a0[dmem][63:0] = (CPU_reset_a0 || CPU_reset_a1) ? 64'b0 :
                         L1_wr_en_a0 ? CPU_dmem_new_word_a1 :
                                  CPU_Dmem_val_a1[dmem][63:0]; end

         // ─────────────────────────────────────────────────────────
         //  WRITEBACK
         // ─────────────────────────────────────────────────────────
         assign CPU_wr_data_a0[63:0] =
            (CPU_is_jal_a0 || CPU_is_jalr_a0) ? (CPU_pc_a0 + 64'd4) :
            CPU_is_lui_a0                 ? CPU_imm_u_a0 :
            CPU_is_auipc_a0                ? (CPU_pc_a0 + CPU_imm_u_a0) :
            CPU_is_load_a0                  ? CPU_load_data_a0 :
                                         CPU_alu_result_a0;

         // ═════════════════════════════════════════════════════════
         //  VIZ — RV64I Single-Cycle Datapath status view. Follows
         //  arm_single_cycle.tlv's proven 'sig'.asBigInt/asInt/asBool
         //  signal-reading convention. Added at the end of Milestone B
         //  (per plan Section 4) now that the full 50-encoding datapath
         //  is stable, rather than re-visualizing a moving target
         //  through Milestones A and B.
   // ─────────────────────────────────────────────────────────────
   //  PASS / FAIL — a small, robust set of final-state checks (the
   //  last write to each of these registers happens near the very end
   //  of the program, nothing overwrites them afterward). Full 50-
   //  encoding coverage is verified via manual trace review against
   //  the expected values documented inline in the program above, per
   //  Milestone B's own done criteria.
   // ─────────────────────────────────────────────────────────────
   assign passed = (CPU_Xreg_val_a1[15] == 64'd1)  &&   // ROM[77] JALR landing
             (CPU_Xreg_val_a1[16] == 64'd1)  &&   // ROM[79] post-FENCE
             (CPU_Xreg_val_a1[30] == 64'd1)  &&   // ROM[39] JAL landing
             (CPU_Xreg_val_a1[10] == 64'd20) &&   // ROM[72] SLLW result
             (CPU_cyc_cnt_a1 > 32'd100);
   assign failed = 1'b0;

   // Milestone C's elfmem store (see trailing \SV block at end of file)
   // references |cpu@0's real mangled SV signal names directly
   // (CPU_is_store_a0, CPU_mem_addr_a0, etc. -- confirmed by inspecting
   // this file's own SandPiper-generated output) rather than bridging
   // through a new *name[N:0] top-level signal: SandPiper generates a
   // bare `assign` for a wide, non-predeclared *name[N:0] without a
   // matching net declaration, which Icarus correctly rejects
   // ("Net ... is not defined in this context") -- confirmed by
   // actually attempting it and reading the real error, not assumed.

//_\SV
   // Milestone C: performs the actual byte-wise store into elfmem.
   // References |cpu@0's real mangled SV signal names directly (see
   // note above this block's *-driven predecessor, removed after
   // confirming SandPiper doesn't correctly declare a new wide
   // *name[N:0] top-level net). Standard synchronous-write timing
   // (non-blocking assignment => value committed and visible starting
   // next clock edge), matching how /dmem's own $wr_en/$val TLV idiom
   // already behaves.
   always_ff @(posedge clk) begin
      if (act4_mode && CPU_is_store_a0) begin
         if (CPU_is_sb_a0) begin
            elfmem[CPU_mem_addr_a0[31:0]+0] <= CPU_rs2_data_a0[7:0];
         end else if (CPU_is_sh_a0) begin
            elfmem[CPU_mem_addr_a0[31:0]+0] <= CPU_rs2_data_a0[7:0];
            elfmem[CPU_mem_addr_a0[31:0]+1] <= CPU_rs2_data_a0[15:8];
         end else if (CPU_is_sw_a0) begin
            elfmem[CPU_mem_addr_a0[31:0]+0] <= CPU_rs2_data_a0[7:0];
            elfmem[CPU_mem_addr_a0[31:0]+1] <= CPU_rs2_data_a0[15:8];
            elfmem[CPU_mem_addr_a0[31:0]+2] <= CPU_rs2_data_a0[23:16];
            elfmem[CPU_mem_addr_a0[31:0]+3] <= CPU_rs2_data_a0[31:24];
         end else if (CPU_is_sd_a0) begin
            elfmem[CPU_mem_addr_a0[31:0]+0] <= CPU_rs2_data_a0[7:0];
            elfmem[CPU_mem_addr_a0[31:0]+1] <= CPU_rs2_data_a0[15:8];
            elfmem[CPU_mem_addr_a0[31:0]+2] <= CPU_rs2_data_a0[23:16];
            elfmem[CPU_mem_addr_a0[31:0]+3] <= CPU_rs2_data_a0[31:24];
            elfmem[CPU_mem_addr_a0[31:0]+4] <= CPU_rs2_data_a0[39:32];
            elfmem[CPU_mem_addr_a0[31:0]+5] <= CPU_rs2_data_a0[47:40];
            elfmem[CPU_mem_addr_a0[31:0]+6] <= CPU_rs2_data_a0[55:48];
            elfmem[CPU_mem_addr_a0[31:0]+7] <= CPU_rs2_data_a0[63:56];
         end
      end
   end
   endmodule


// Undefine macros defined by SandPiper (in "rv64i_core_gen.sv").
`undef BOGUS_USE
