// Generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro from Redwood EDA, LLC.
// Redwood EDA, LLC does not claim intellectual property rights to this file and provides no warranty regarding its correctness or quality.


// For silencing unused signal messages.
`define BOGUS_USE(ignore)


`include "sandpiper_gen.vh"


genvar dmem, vreg, xreg;


//
// Signals declared top-level.
//

// For |cpu$alt_pc.
logic [63:0] CPU_alt_pc_a0,
             CPU_alt_pc_a1;

// For |cpu$alu_op2.
logic [63:0] CPU_alu_op2_a0;

// For |cpu$alu_result.
logic [63:0] CPU_alu_result_a0;

// For |cpu$alu_result32.
logic [63:0] CPU_alu_result32_a0;

// For |cpu$alu_result32_raw.
logic [31:0] CPU_alu_result32_raw_a0;

// For |cpu$alu_result64.
logic [63:0] CPU_alu_result64_a0;

// For |cpu$alu_sra64.
logic [63:0] CPU_alu_sra64_a0;

// For |cpu$alu_sraw32_wide.
logic [63:0] CPU_alu_sraw32_wide_a0;

// For |cpu$blt_signed.
logic CPU_blt_signed_a0;

// For |cpu$branch_taken.
logic CPU_branch_taken_a0;

// For |cpu$branch_target.
logic [63:0] CPU_branch_target_a0;

// For |cpu$csr_addr.
logic [11:0] CPU_csr_addr_a0;

// For |cpu$csr_is_mcause.
logic CPU_csr_is_mcause_a0;

// For |cpu$csr_is_mepc.
logic CPU_csr_is_mepc_a0,
      CPU_csr_is_mepc_a1;

// For |cpu$csr_is_mtval.
logic CPU_csr_is_mtval_a0;

// For |cpu$csr_is_mtvec.
logic CPU_csr_is_mtvec_a0,
      CPU_csr_is_mtvec_a1;

// For |cpu$csr_is_veda_attr.
logic CPU_csr_is_veda_attr_a0,
      CPU_csr_is_veda_attr_a1;

// For |cpu$csr_is_veda_mepcc_base.
logic CPU_csr_is_veda_mepcc_base_a0,
      CPU_csr_is_veda_mepcc_base_a1;

// For |cpu$csr_is_veda_mepcc_length.
logic CPU_csr_is_veda_mepcc_length_a0,
      CPU_csr_is_veda_mepcc_length_a1;

// For |cpu$csr_is_veda_pcc_base.
logic CPU_csr_is_veda_pcc_base_a0,
      CPU_csr_is_veda_pcc_base_a1;

// For |cpu$csr_is_veda_pcc_length.
logic CPU_csr_is_veda_pcc_length_a0,
      CPU_csr_is_veda_pcc_length_a1;

// For |cpu$csr_rdata.
logic [63:0] CPU_csr_rdata_a0;

// For |cpu$csr_wdata.
logic [63:0] CPU_csr_wdata_a0,
             CPU_csr_wdata_a1;

// For |cpu$csr_write_en.
logic CPU_csr_write_en_a0,
      CPU_csr_write_en_a1;

// For |cpu$cyc_cnt.
logic [31:0] CPU_cyc_cnt_a0,
             CPU_cyc_cnt_a1;

// For |cpu$dmem_new_word.
logic [63:0] CPU_dmem_new_word_a0,
             CPU_dmem_new_word_a1;

// For |cpu$funct3.
logic [2:0] CPU_funct3_a0;

// For |cpu$funct6.
logic [5:0] CPU_funct6_a0;

// For |cpu$funct7.
logic [6:0] CPU_funct7_a0;

// For |cpu$imm_b.
logic [63:0] CPU_imm_b_a0;

// For |cpu$imm_i.
logic [63:0] CPU_imm_i_a0;

// For |cpu$imm_j.
logic [63:0] CPU_imm_j_a0;

// For |cpu$imm_s.
logic [63:0] CPU_imm_s_a0;

// For |cpu$imm_u.
logic [63:0] CPU_imm_u_a0;

// For |cpu$instr.
logic [31:0] CPU_instr_a0;

// For |cpu$instr_elf.
logic [31:0] CPU_instr_elf_a0;

// For |cpu$instr_rom.
logic [31:0] CPU_instr_rom_a0;

// For |cpu$is_add.
logic CPU_is_add_a0;

// For |cpu$is_addi.
logic CPU_is_addi_a0;

// For |cpu$is_addiw.
logic CPU_is_addiw_a0;

// For |cpu$is_addw.
logic CPU_is_addw_a0;

// For |cpu$is_alu_imm.
logic CPU_is_alu_imm_a0;

// For |cpu$is_alu_immw.
logic CPU_is_alu_immw_a0;

// For |cpu$is_alu_reg.
logic CPU_is_alu_reg_a0;

// For |cpu$is_alu_regw.
logic CPU_is_alu_regw_a0;

// For |cpu$is_and.
logic CPU_is_and_a0;

// For |cpu$is_andi.
logic CPU_is_andi_a0;

// For |cpu$is_auipc.
logic CPU_is_auipc_a0;

// For |cpu$is_beq.
logic CPU_is_beq_a0;

// For |cpu$is_bge.
logic CPU_is_bge_a0;

// For |cpu$is_bgeu.
logic CPU_is_bgeu_a0;

// For |cpu$is_blt.
logic CPU_is_blt_a0;

// For |cpu$is_bltu.
logic CPU_is_bltu_a0;

// For |cpu$is_bne.
logic CPU_is_bne_a0;

// For |cpu$is_csr_access.
logic CPU_is_csr_access_a0;

// For |cpu$is_csrrs.
logic CPU_is_csrrs_a0;

// For |cpu$is_csrrw.
logic CPU_is_csrrw_a0;

// For |cpu$is_fence.
logic CPU_is_fence_a0;

// For |cpu$is_jal.
logic CPU_is_jal_a0;

// For |cpu$is_jalr.
logic CPU_is_jalr_a0;

// For |cpu$is_lb.
logic CPU_is_lb_a0;

// For |cpu$is_lbu.
logic CPU_is_lbu_a0;

// For |cpu$is_ld.
logic CPU_is_ld_a0;

// For |cpu$is_lh.
logic CPU_is_lh_a0;

// For |cpu$is_lhu.
logic CPU_is_lhu_a0;

// For |cpu$is_load.
logic CPU_is_load_a0;

// For |cpu$is_lui.
logic CPU_is_lui_a0;

// For |cpu$is_lw.
logic CPU_is_lw_a0;

// For |cpu$is_lwu.
logic CPU_is_lwu_a0;

// For |cpu$is_mret.
logic CPU_is_mret_a0;

// For |cpu$is_or.
logic CPU_is_or_a0;

// For |cpu$is_ori.
logic CPU_is_ori_a0;

// For |cpu$is_sb.
logic CPU_is_sb_a0;

// For |cpu$is_sd.
logic CPU_is_sd_a0;

// For |cpu$is_sh.
logic CPU_is_sh_a0;

// For |cpu$is_shift_imm.
logic CPU_is_shift_imm_a0;

// For |cpu$is_shift_immw.
logic CPU_is_shift_immw_a0;

// For |cpu$is_sll.
logic CPU_is_sll_a0;

// For |cpu$is_slli.
logic CPU_is_slli_a0;

// For |cpu$is_slliw.
logic CPU_is_slliw_a0;

// For |cpu$is_sllw.
logic CPU_is_sllw_a0;

// For |cpu$is_slt.
logic CPU_is_slt_a0;

// For |cpu$is_slti.
logic CPU_is_slti_a0;

// For |cpu$is_sltiu.
logic CPU_is_sltiu_a0;

// For |cpu$is_sltu.
logic CPU_is_sltu_a0;

// For |cpu$is_sra.
logic CPU_is_sra_a0;

// For |cpu$is_srai.
logic CPU_is_srai_a0;

// For |cpu$is_sraiw.
logic CPU_is_sraiw_a0;

// For |cpu$is_sraw.
logic CPU_is_sraw_a0;

// For |cpu$is_srl.
logic CPU_is_srl_a0;

// For |cpu$is_srli.
logic CPU_is_srli_a0;

// For |cpu$is_srliw.
logic CPU_is_srliw_a0;

// For |cpu$is_srlw.
logic CPU_is_srlw_a0;

// For |cpu$is_store.
logic CPU_is_store_a0,
      CPU_is_store_a1;

// For |cpu$is_sub.
logic CPU_is_sub_a0;

// For |cpu$is_subw.
logic CPU_is_subw_a0;

// For |cpu$is_sw.
logic CPU_is_sw_a0;

// For |cpu$is_veda_atomic.
logic CPU_is_veda_atomic_a0;

// For |cpu$is_veda_bind.
logic CPU_is_veda_bind_a0;

// For |cpu$is_veda_bind_notrap.
logic CPU_is_veda_bind_notrap_a0,
      CPU_is_veda_bind_notrap_a1;

// For |cpu$is_veda_bind_plain.
logic CPU_is_veda_bind_plain_a0,
      CPU_is_veda_bind_plain_a1;

// For |cpu$is_veda_capquery.
logic CPU_is_veda_capquery_a0;

// For |cpu$is_veda_cgetaddr.
logic CPU_is_veda_cgetaddr_a0;

// For |cpu$is_veda_cgetbase.
logic CPU_is_veda_cgetbase_a0;

// For |cpu$is_veda_cgetlen.
logic CPU_is_veda_cgetlen_a0;

// For |cpu$is_veda_cgetoffset.
logic CPU_is_veda_cgetoffset_a0;

// For |cpu$is_veda_cgetperm.
logic CPU_is_veda_cgetperm_a0;

// For |cpu$is_veda_cgettag.
logic CPU_is_veda_cgettag_a0;

// For |cpu$is_veda_cgettype.
logic CPU_is_veda_cgettype_a0;

// For |cpu$is_veda_cseal.
logic CPU_is_veda_cseal_a0,
      CPU_is_veda_cseal_a1;

// For |cpu$is_veda_csetbounds.
logic CPU_is_veda_csetbounds_a0;

// For |cpu$is_veda_csetbounds_either.
logic CPU_is_veda_csetbounds_either_a0,
      CPU_is_veda_csetbounds_either_a1;

// For |cpu$is_veda_csetboundsexact.
logic CPU_is_veda_csetboundsexact_a0;

// For |cpu$is_veda_cunseal.
logic CPU_is_veda_cunseal_a0,
      CPU_is_veda_cunseal_a1;

// For |cpu$is_veda_droppriv.
logic CPU_is_veda_droppriv_a0,
      CPU_is_veda_droppriv_a1;

// For |cpu$is_veda_nmc_add_d.
logic CPU_is_veda_nmc_add_d_a0;

// For |cpu$is_veda_nmc_add_w.
logic CPU_is_veda_nmc_add_w_a0;

// For |cpu$is_veda_oca.
logic CPU_is_veda_oca_a0,
      CPU_is_veda_oca_a1;

// For |cpu$is_veda_ocinvoke.
logic CPU_is_veda_ocinvoke_a0,
      CPU_is_veda_ocinvoke_a1;

// For |cpu$is_veda_ocjalr.
logic CPU_is_veda_ocjalr_a0;

// For |cpu$is_veda_ocl.
logic CPU_is_veda_ocl_a0;

// For |cpu$is_veda_ocl_c.
logic CPU_is_veda_ocl_c_a0,
      CPU_is_veda_ocl_c_a1;

// For |cpu$is_veda_ocs.
logic CPU_is_veda_ocs_a0;

// For |cpu$is_veda_ocs_c.
logic CPU_is_veda_ocs_c_a0;

// For |cpu$is_veda_odt_destroy.
logic CPU_is_veda_odt_destroy_a0;

// For |cpu$is_veda_odt_populate.
logic CPU_is_veda_odt_populate_a0;

// For |cpu$is_veda_odt_populate_fast.
logic CPU_is_veda_odt_populate_fast_a0;

// For |cpu$is_veda_ospecialrw.
logic CPU_is_veda_ospecialrw_a0,
      CPU_is_veda_ospecialrw_a1;

// For |cpu$is_veda_rebind.
logic CPU_is_veda_rebind_a0,
      CPU_is_veda_rebind_a1;

// For |cpu$is_w_op.
logic CPU_is_w_op_a0;

// For |cpu$is_xor.
logic CPU_is_xor_a0;

// For |cpu$is_xori.
logic CPU_is_xori_a0;

// For |cpu$jal_target.
logic [63:0] CPU_jal_target_a0;

// For |cpu$jalr_target.
logic [63:0] CPU_jalr_target_a0;

// For |cpu$load_data.
logic [63:0] CPU_load_data_a0;

// For |cpu$lt_signed.
logic CPU_lt_signed_a0;

// For |cpu$lt_unsigned.
logic CPU_lt_unsigned_a0;

// For |cpu$mcause.
logic [63:0] CPU_mcause_a0,
             CPU_mcause_a1;

// For |cpu$mem_addr.
logic [63:0] CPU_mem_addr_a0;

// For |cpu$mem_byte_off.
logic [2:0] CPU_mem_byte_off_a0;

// For |cpu$mem_bytes_elf.
logic [63:0] CPU_mem_bytes_elf_a0;

// For |cpu$mem_cur_word.
logic [63:0] CPU_mem_cur_word_a0;

// For |cpu$mem_shift_bits.
logic [5:0] CPU_mem_shift_bits_a0;

// For |cpu$mem_shifted.
logic [63:0] CPU_mem_shifted_a0;

// For |cpu$mem_word_idx.
logic [5:0] CPU_mem_word_idx_a0,
            CPU_mem_word_idx_a1;

// For |cpu$mepc.
logic [63:0] CPU_mepc_a0,
             CPU_mepc_a1;

// For |cpu$mtval.
logic [63:0] CPU_mtval_a0,
             CPU_mtval_a1;

// For |cpu$mtvec.
logic [63:0] CPU_mtvec_a0,
             CPU_mtvec_a1;

// For |cpu$op_is_auipc.
logic CPU_op_is_auipc_a0;

// For |cpu$op_is_branch.
logic CPU_op_is_branch_a0;

// For |cpu$op_is_custom0.
logic CPU_op_is_custom0_a0;

// For |cpu$op_is_custom1.
logic CPU_op_is_custom1_a0;

// For |cpu$op_is_custom2.
logic CPU_op_is_custom2_a0;

// For |cpu$op_is_custom3.
logic CPU_op_is_custom3_a0;

// For |cpu$op_is_fence.
logic CPU_op_is_fence_a0;

// For |cpu$op_is_imm.
logic CPU_op_is_imm_a0;

// For |cpu$op_is_immw.
logic CPU_op_is_immw_a0;

// For |cpu$op_is_jal.
logic CPU_op_is_jal_a0;

// For |cpu$op_is_jalr.
logic CPU_op_is_jalr_a0;

// For |cpu$op_is_load.
logic CPU_op_is_load_a0;

// For |cpu$op_is_lui.
logic CPU_op_is_lui_a0;

// For |cpu$op_is_reg.
logic CPU_op_is_reg_a0;

// For |cpu$op_is_regw.
logic CPU_op_is_regw_a0;

// For |cpu$op_is_store.
logic CPU_op_is_store_a0;

// For |cpu$op_is_system.
logic CPU_op_is_system_a0;

// For |cpu$opcode.
logic [6:0] CPU_opcode_a0;

// For |cpu$pc.
logic [63:0] CPU_pc_a0,
             CPU_pc_a1;

// For |cpu$pc_src.
logic CPU_pc_src_a0,
      CPU_pc_src_a1;

// For |cpu$priv.
logic CPU_priv_a0,
      CPU_priv_a1;

// For |cpu$rd.
logic [4:0] CPU_rd_a0,
            CPU_rd_a1;

// For |cpu$reg_write.
logic CPU_reg_write_a0,
      CPU_reg_write_a1;

// For |cpu$reset.
logic CPU_reset_a0,
      CPU_reset_a1;

// For |cpu$reset_just_released.
logic CPU_reset_just_released_a0;

// For |cpu$rs1.
logic [4:0] CPU_rs1_a0;

// For |cpu$rs1_data.
logic [63:0] CPU_rs1_data_a0;

// For |cpu$rs2.
logic [4:0] CPU_rs2_a0;

// For |cpu$rs2_data.
logic [63:0] CPU_rs2_data_a0;

// For |cpu$shamt5.
logic [4:0] CPU_shamt5_a0;

// For |cpu$shamt6.
logic [5:0] CPU_shamt6_a0;

// For |cpu$shift_amt32.
logic [4:0] CPU_shift_amt32_a0;

// For |cpu$shift_amt64.
logic [5:0] CPU_shift_amt64_a0;

// For |cpu$sra_ext128.
logic [127:0] CPU_sra_ext128_a0;

// For |cpu$sraw_ext64.
logic [63:0] CPU_sraw_ext64_a0;

// For |cpu$store_data_sh.
logic [63:0] CPU_store_data_sh_a0;

// For |cpu$store_mask.
logic [63:0] CPU_store_mask_a0;

// For |cpu$store_mask_base.
logic [63:0] CPU_store_mask_base_a0;

// For |cpu$veda_atomic_cause.
logic [4:0] CPU_veda_atomic_cause_a0;

// For |cpu$veda_atomic_lt_signed.
logic CPU_veda_atomic_lt_signed_a0;

// For |cpu$veda_atomic_op.
logic [4:0] CPU_veda_atomic_op_a0;

// For |cpu$veda_atomic_result.
logic [63:0] CPU_veda_atomic_result_a0;

// For |cpu$veda_atomic_violation.
logic CPU_veda_atomic_violation_a0;

// For |cpu$veda_attr.
logic [31:0] CPU_veda_attr_a0,
             CPU_veda_attr_a1;

// For |cpu$veda_baseisa_store_granule.
logic [31:0] CPU_veda_baseisa_store_granule_a0;

// For |cpu$veda_baseisa_store_in_range.
logic CPU_veda_baseisa_store_in_range_a0;

// For |cpu$veda_bind_cause.
logic [4:0] CPU_veda_bind_cause_a0;

// For |cpu$veda_bind_claim_en.
logic CPU_veda_bind_claim_en_a0;

// For |cpu$veda_bind_mode.
logic [1:0] CPU_veda_bind_mode_a0;

// For |cpu$veda_bind_notfound_violation.
logic CPU_veda_bind_notfound_violation_a0;

// For |cpu$veda_bind_owner_violation.
logic CPU_veda_bind_owner_violation_a0;

// For |cpu$veda_bind_trap.
logic CPU_veda_bind_trap_a0,
      CPU_veda_bind_trap_a1;

// For |cpu$veda_bounds_ok.
logic CPU_veda_bounds_ok_a0;

// For |cpu$veda_cap_old_d.
logic [63:0] CPU_veda_cap_old_d_a0;

// For |cpu$veda_cap_old_w.
logic [31:0] CPU_veda_cap_old_w_a0;

// For |cpu$veda_cap_real_addr.
logic [63:0] CPU_veda_cap_real_addr_a0;

// For |cpu$veda_capmem_granule.
logic [31:0] CPU_veda_capmem_granule_a0;

// For |cpu$veda_capmem_nmc_granule.
logic [31:0] CPU_veda_capmem_nmc_granule_a0;

// For |cpu$veda_capquery_result.
logic [63:0] CPU_veda_capquery_result_a0;

// For |cpu$veda_check_odt_addr.
logic [31:0] CPU_veda_check_odt_addr_a0;

// For |cpu$veda_check_odt_gen.
logic [7:0] CPU_veda_check_odt_gen_a0;

// For |cpu$veda_check_odt_id_hi.
logic [14:0] CPU_veda_check_odt_id_hi_a0;

// For |cpu$veda_check_odt_id_match.
logic CPU_veda_check_odt_id_match_a0;

// For |cpu$veda_check_odt_idx.
logic [7:0] CPU_veda_check_odt_idx_a0;

// For |cpu$veda_check_odt_valid.
logic CPU_veda_check_odt_valid_a0;

// For |cpu$veda_cs2_base.
logic [31:0] CPU_veda_cs2_base_a0,
             CPU_veda_cs2_base_a1;

// For |cpu$veda_cs2_length.
logic [15:0] CPU_veda_cs2_length_a0,
             CPU_veda_cs2_length_a1;

// For |cpu$veda_cs2_object_id.
logic [22:0] CPU_veda_cs2_object_id_a0,
             CPU_veda_cs2_object_id_a1;

// For |cpu$veda_cs2_offset.
logic [15:0] CPU_veda_cs2_offset_a0,
             CPU_veda_cs2_offset_a1;

// For |cpu$veda_cs2_otype.
logic [15:0] CPU_veda_cs2_otype_a0;

// For |cpu$veda_cs2_perms.
logic [15:0] CPU_veda_cs2_perms_a0,
             CPU_veda_cs2_perms_a1;

// For |cpu$veda_cs2_reserved.
logic [7:0] CPU_veda_cs2_reserved_a0,
            CPU_veda_cs2_reserved_a1;

// For |cpu$veda_cs2_sealed.
logic CPU_veda_cs2_sealed_a0;

// For |cpu$veda_cs2_tag.
logic CPU_veda_cs2_tag_a0;

// For |cpu$veda_cseal_authorized.
logic CPU_veda_cseal_authorized_a0;

// For |cpu$veda_cseal_cunseal_rs2_cap.
logic [3:0] CPU_veda_cseal_cunseal_rs2_cap_a0;

// For |cpu$veda_cseal_ok.
logic CPU_veda_cseal_ok_a0,
      CPU_veda_cseal_ok_a1;

// For |cpu$veda_csetbounds_new_base.
logic [31:0] CPU_veda_csetbounds_new_base_a0,
             CPU_veda_csetbounds_new_base_a1;

// For |cpu$veda_csetbounds_new_length.
logic [15:0] CPU_veda_csetbounds_new_length_a0,
             CPU_veda_csetbounds_new_length_a1;

// For |cpu$veda_csetbounds_ok.
logic CPU_veda_csetbounds_ok_a0,
      CPU_veda_csetbounds_ok_a1;

// For |cpu$veda_csetbounds_window_ok.
logic CPU_veda_csetbounds_window_ok_a0;

// For |cpu$veda_cunseal_authorized.
logic CPU_veda_cunseal_authorized_a0;

// For |cpu$veda_cunseal_ok.
logic CPU_veda_cunseal_ok_a0,
      CPU_veda_cunseal_ok_a1;

// For |cpu$veda_gen_stale.
logic CPU_veda_gen_stale_a0;

// For |cpu$veda_mepcc_base.
logic [31:0] CPU_veda_mepcc_base_a0,
             CPU_veda_mepcc_base_a1;

// For |cpu$veda_mepcc_length.
logic [15:0] CPU_veda_mepcc_length_a0,
             CPU_veda_mepcc_length_a1;

// For |cpu$veda_nmc_add_d_cause.
logic [4:0] CPU_veda_nmc_add_d_cause_a0;

// For |cpu$veda_nmc_add_d_violation.
logic CPU_veda_nmc_add_d_violation_a0;

// For |cpu$veda_nmc_add_result_d.
logic [63:0] CPU_veda_nmc_add_result_d_a0;

// For |cpu$veda_nmc_add_result_w.
logic [31:0] CPU_veda_nmc_add_result_w_a0;

// For |cpu$veda_nmc_add_w_cause.
logic [4:0] CPU_veda_nmc_add_w_cause_a0;

// For |cpu$veda_nmc_add_w_violation.
logic CPU_veda_nmc_add_w_violation_a0;

// For |cpu$veda_nmc_bounds_ok_d.
logic CPU_veda_nmc_bounds_ok_d_a0;

// For |cpu$veda_nmc_bounds_ok_w.
logic CPU_veda_nmc_bounds_ok_w_a0;

// For |cpu$veda_nmc_rd_value.
logic [63:0] CPU_veda_nmc_rd_value_a0;

// For |cpu$veda_object_id.
logic [22:0] CPU_veda_object_id_a0,
             CPU_veda_object_id_a1;

// For |cpu$veda_oca_ok.
logic CPU_veda_oca_ok_a0,
      CPU_veda_oca_ok_a1;

// For |cpu$veda_oca_out_of_range.
logic CPU_veda_oca_out_of_range_a0;

// For |cpu$veda_oca_sum.
logic [63:0] CPU_veda_oca_sum_a0;
logic [15:0] CPU_veda_oca_sum_a1;

// For |cpu$veda_ocinvoke_cap_idx.
logic [3:0] CPU_veda_ocinvoke_cap_idx_a0;

// For |cpu$veda_ocinvoke_cause.
logic [4:0] CPU_veda_ocinvoke_cause_a0;

// For |cpu$veda_ocinvoke_target.
logic [63:0] CPU_veda_ocinvoke_target_a0;

// For |cpu$veda_ocinvoke_violation.
logic CPU_veda_ocinvoke_violation_a0,
      CPU_veda_ocinvoke_violation_a1;

// For |cpu$veda_ocjalr_cap_idx.
logic [3:0] CPU_veda_ocjalr_cap_idx_a0;

// For |cpu$veda_ocjalr_cause.
logic [4:0] CPU_veda_ocjalr_cause_a0;

// For |cpu$veda_ocjalr_target.
logic [63:0] CPU_veda_ocjalr_target_a0;

// For |cpu$veda_ocjalr_violation.
logic CPU_veda_ocjalr_violation_a0;

// For |cpu$veda_ocl_cause.
logic [4:0] CPU_veda_ocl_cause_a0;

// For |cpu$veda_ocl_load_data.
logic [63:0] CPU_veda_ocl_load_data_a0;

// For |cpu$veda_ocl_ocs_rs1_cap.
logic [3:0] CPU_veda_ocl_ocs_rs1_cap_a0;

// For |cpu$veda_ocl_violation.
logic CPU_veda_ocl_violation_a0;

// For |cpu$veda_oclc_bounds_ok.
logic CPU_veda_oclc_bounds_ok_a0;

// For |cpu$veda_oclc_cause.
logic [4:0] CPU_veda_oclc_cause_a0;

// For |cpu$veda_oclc_load_data.
logic [127:0] CPU_veda_oclc_load_data_a0;

// For |cpu$veda_oclc_loaded_tag.
logic CPU_veda_oclc_loaded_tag_a0,
      CPU_veda_oclc_loaded_tag_a1;

// For |cpu$veda_oclc_unpacked_base.
logic [31:0] CPU_veda_oclc_unpacked_base_a0,
             CPU_veda_oclc_unpacked_base_a1;

// For |cpu$veda_oclc_unpacked_length.
logic [15:0] CPU_veda_oclc_unpacked_length_a0,
             CPU_veda_oclc_unpacked_length_a1;

// For |cpu$veda_oclc_unpacked_object_id.
logic [22:0] CPU_veda_oclc_unpacked_object_id_a0,
             CPU_veda_oclc_unpacked_object_id_a1;

// For |cpu$veda_oclc_unpacked_offset.
logic [15:0] CPU_veda_oclc_unpacked_offset_a0,
             CPU_veda_oclc_unpacked_offset_a1;

// For |cpu$veda_oclc_unpacked_otype.
logic [15:0] CPU_veda_oclc_unpacked_otype_a0,
             CPU_veda_oclc_unpacked_otype_a1;

// For |cpu$veda_oclc_unpacked_perms.
logic [15:0] CPU_veda_oclc_unpacked_perms_a0,
             CPU_veda_oclc_unpacked_perms_a1;

// For |cpu$veda_oclc_unpacked_reserved.
logic [7:0] CPU_veda_oclc_unpacked_reserved_a0,
            CPU_veda_oclc_unpacked_reserved_a1;

// For |cpu$veda_oclc_violation.
logic CPU_veda_oclc_violation_a0,
      CPU_veda_oclc_violation_a1;

// For |cpu$veda_ocs_cause.
logic [4:0] CPU_veda_ocs_cause_a0;

// For |cpu$veda_ocs_value.
logic [63:0] CPU_veda_ocs_value_a0;

// For |cpu$veda_ocs_violation.
logic CPU_veda_ocs_violation_a0;

// For |cpu$veda_ocsc_cause.
logic [4:0] CPU_veda_ocsc_cause_a0;

// For |cpu$veda_ocsc_packed.
logic [127:0] CPU_veda_ocsc_packed_a0;

// For |cpu$veda_ocsc_store_cap_base.
logic [31:0] CPU_veda_ocsc_store_cap_base_a0;

// For |cpu$veda_ocsc_store_cap_length.
logic [15:0] CPU_veda_ocsc_store_cap_length_a0;

// For |cpu$veda_ocsc_store_cap_object_id.
logic [22:0] CPU_veda_ocsc_store_cap_object_id_a0;

// For |cpu$veda_ocsc_store_cap_offset.
logic [15:0] CPU_veda_ocsc_store_cap_offset_a0;

// For |cpu$veda_ocsc_store_cap_otype.
logic [15:0] CPU_veda_ocsc_store_cap_otype_a0;

// For |cpu$veda_ocsc_store_cap_perms.
logic [15:0] CPU_veda_ocsc_store_cap_perms_a0;

// For |cpu$veda_ocsc_store_cap_reserved.
logic [7:0] CPU_veda_ocsc_store_cap_reserved_a0;

// For |cpu$veda_ocsc_store_tag.
logic CPU_veda_ocsc_store_tag_a0;

// For |cpu$veda_ocsc_violation.
logic CPU_veda_ocsc_violation_a0;

// For |cpu$veda_oda_authorized.
logic CPU_veda_oda_authorized_a0;

// For |cpu$veda_oda_base.
logic [31:0] CPU_veda_oda_base_a0,
             CPU_veda_oda_base_a1;

// For |cpu$veda_oda_length.
logic [15:0] CPU_veda_oda_length_a0,
             CPU_veda_oda_length_a1;

// For |cpu$veda_oda_object_id.
logic [22:0] CPU_veda_oda_object_id_a0,
             CPU_veda_oda_object_id_a1;

// For |cpu$veda_oda_offset.
logic [15:0] CPU_veda_oda_offset_a0,
             CPU_veda_oda_offset_a1;

// For |cpu$veda_oda_otype.
logic [15:0] CPU_veda_oda_otype_a0,
             CPU_veda_oda_otype_a1;

// For |cpu$veda_oda_perms.
logic [15:0] CPU_veda_oda_perms_a0,
             CPU_veda_oda_perms_a1;

// For |cpu$veda_oda_reserved.
logic [7:0] CPU_veda_oda_reserved_a0,
            CPU_veda_oda_reserved_a1;

// For |cpu$veda_oda_sealed.
logic CPU_veda_oda_sealed_a0;

// For |cpu$veda_oda_tag.
logic CPU_veda_oda_tag_a0,
      CPU_veda_oda_tag_a1;

// For |cpu$veda_odt_addr.
logic [31:0] CPU_veda_odt_addr_a0;

// For |cpu$veda_odt_base.
logic [31:0] CPU_veda_odt_base_a0,
             CPU_veda_odt_base_a1;

// For |cpu$veda_odt_destroy_violation.
logic CPU_veda_odt_destroy_violation_a0;

// For |cpu$veda_odt_gen.
logic [7:0] CPU_veda_odt_gen_a0,
            CPU_veda_odt_gen_a1;

// For |cpu$veda_odt_id_hi.
logic [14:0] CPU_veda_odt_id_hi_a0;

// For |cpu$veda_odt_id_match.
logic CPU_veda_odt_id_match_a0;

// For |cpu$veda_odt_idx.
logic [7:0] CPU_veda_odt_idx_a0;

// For |cpu$veda_odt_length.
logic [15:0] CPU_veda_odt_length_a0,
             CPU_veda_odt_length_a1;

// For |cpu$veda_odt_owner.
logic [7:0] CPU_veda_odt_owner_a0;

// For |cpu$veda_odt_perms.
logic [15:0] CPU_veda_odt_perms_a0,
             CPU_veda_odt_perms_a1;

// For |cpu$veda_odt_populate_violation.
logic CPU_veda_odt_populate_violation_a0;

// For |cpu$veda_odt_retired.
logic CPU_veda_odt_retired_a0;

// For |cpu$veda_odt_valid.
logic CPU_veda_odt_valid_a0,
      CPU_veda_odt_valid_a1;

// For |cpu$veda_odtpd_new_base.
logic [31:0] CPU_veda_odtpd_new_base_a0;

// For |cpu$veda_odtpd_new_gen.
logic [7:0] CPU_veda_odtpd_new_gen_a0;

// For |cpu$veda_odtpd_new_length.
logic [15:0] CPU_veda_odtpd_new_length_a0;

// For |cpu$veda_odtpd_new_perms.
logic [15:0] CPU_veda_odtpd_new_perms_a0;

// For |cpu$veda_odtpd_new_retired.
logic CPU_veda_odtpd_new_retired_a0;

// For |cpu$veda_ospecialrw_violation.
logic CPU_veda_ospecialrw_violation_a0,
      CPU_veda_ospecialrw_violation_a1;

// For |cpu$veda_owner_claim_en.
logic CPU_veda_owner_claim_en_a0;

// For |cpu$veda_owner_ok.
logic CPU_veda_owner_ok_a0,
      CPU_veda_owner_ok_a1;

// For |cpu$veda_pcc_base.
logic [31:0] CPU_veda_pcc_base_a0,
             CPU_veda_pcc_base_a1;

// For |cpu$veda_pcc_length.
logic [15:0] CPU_veda_pcc_length_a0,
             CPU_veda_pcc_length_a1;

// For |cpu$veda_pcc_violation.
logic CPU_veda_pcc_violation_a0,
      CPU_veda_pcc_violation_a1;

// For |cpu$veda_perm_load_ok.
logic CPU_veda_perm_load_ok_a0;

// For |cpu$veda_perm_nmc_ok.
logic CPU_veda_perm_nmc_ok_a0;

// For |cpu$veda_perm_store_ok.
logic CPU_veda_perm_store_ok_a0;

// For |cpu$veda_rd_cap.
logic [3:0] CPU_veda_rd_cap_a0,
            CPU_veda_rd_cap_a1;

// For |cpu$veda_rdcap_otype.
logic [15:0] CPU_veda_rdcap_otype_a0;

// For |cpu$veda_real_addr.
logic [63:0] CPU_veda_real_addr_a0;

// For |cpu$veda_rebind_claim_en.
logic CPU_veda_rebind_claim_en_a0;

// For |cpu$veda_rebind_ok.
logic CPU_veda_rebind_ok_a0,
      CPU_veda_rebind_ok_a1;

// For |cpu$veda_rebind_sealed.
logic CPU_veda_rebind_sealed_a0;

// For |cpu$veda_rs1cap_base.
logic [31:0] CPU_veda_rs1cap_base_a0,
             CPU_veda_rs1cap_base_a1;

// For |cpu$veda_rs1cap_length.
logic [15:0] CPU_veda_rs1cap_length_a0,
             CPU_veda_rs1cap_length_a1;

// For |cpu$veda_rs1cap_object_id.
logic [22:0] CPU_veda_rs1cap_object_id_a0,
             CPU_veda_rs1cap_object_id_a1;

// For |cpu$veda_rs1cap_offset.
logic [15:0] CPU_veda_rs1cap_offset_a0,
             CPU_veda_rs1cap_offset_a1;

// For |cpu$veda_rs1cap_otype.
logic [15:0] CPU_veda_rs1cap_otype_a0,
             CPU_veda_rs1cap_otype_a1;

// For |cpu$veda_rs1cap_perms.
logic [15:0] CPU_veda_rs1cap_perms_a0,
             CPU_veda_rs1cap_perms_a1;

// For |cpu$veda_rs1cap_reserved.
logic [7:0] CPU_veda_rs1cap_reserved_a0,
            CPU_veda_rs1cap_reserved_a1;

// For |cpu$veda_rs1cap_tag.
logic CPU_veda_rs1cap_tag_a0,
      CPU_veda_rs1cap_tag_a1;

// For |cpu$veda_sealed.
logic CPU_veda_sealed_a0;

// For |cpu$veda_trap_cap_idx.
logic [3:0] CPU_veda_trap_cap_idx_a0,
            CPU_veda_trap_cap_idx_a1;

// For |cpu$veda_trap_cause.
logic [4:0] CPU_veda_trap_cause_a0,
            CPU_veda_trap_cause_a1;

// For |cpu$veda_trap_taken.
logic CPU_veda_trap_taken_a0,
      CPU_veda_trap_taken_a1;

// For |cpu$veda_violation.
logic CPU_veda_violation_a0;

// For |cpu$wr_data.
logic [63:0] CPU_wr_data_a0,
             CPU_wr_data_a1;

// For |cpu/dmem$val.
logic [63:0] CPU_Dmem_val_a0 [63:0],
             CPU_Dmem_val_a1 [63:0];

// For |cpu/vreg$base.
logic [31:0] CPU_Vreg_base_a0 [15:0],
             CPU_Vreg_base_a1 [15:0];

// For |cpu/vreg$length.
logic [15:0] CPU_Vreg_length_a0 [15:0],
             CPU_Vreg_length_a1 [15:0];

// For |cpu/vreg$object_id.
logic [22:0] CPU_Vreg_object_id_a0 [15:0],
             CPU_Vreg_object_id_a1 [15:0];

// For |cpu/vreg$offset.
logic [15:0] CPU_Vreg_offset_a0 [15:0],
             CPU_Vreg_offset_a1 [15:0];

// For |cpu/vreg$otype.
logic [15:0] CPU_Vreg_otype_a0 [15:0],
             CPU_Vreg_otype_a1 [15:0];

// For |cpu/vreg$perms.
logic [15:0] CPU_Vreg_perms_a0 [15:0],
             CPU_Vreg_perms_a1 [15:0];

// For |cpu/vreg$reserved.
logic [7:0] CPU_Vreg_reserved_a0 [15:0],
            CPU_Vreg_reserved_a1 [15:0];

// For |cpu/vreg$tag.
logic CPU_Vreg_tag_a0 [15:0],
      CPU_Vreg_tag_a1 [15:0];

// For |cpu/xreg$val.
logic [63:0] CPU_Xreg_val_a0 [31:0],
             CPU_Xreg_val_a1 [31:0];




   //
   // Scope: |cpu
   //

      // Staging of $alt_pc.
      always_ff @(posedge clk) CPU_alt_pc_a1[63:0] <= CPU_alt_pc_a0[63:0];

      // Staging of $csr_is_mepc.
      always_ff @(posedge clk) CPU_csr_is_mepc_a1 <= CPU_csr_is_mepc_a0;

      // Staging of $csr_is_mtvec.
      always_ff @(posedge clk) CPU_csr_is_mtvec_a1 <= CPU_csr_is_mtvec_a0;

      // Staging of $csr_is_veda_attr.
      always_ff @(posedge clk) CPU_csr_is_veda_attr_a1 <= CPU_csr_is_veda_attr_a0;

      // Staging of $csr_is_veda_mepcc_base.
      always_ff @(posedge clk) CPU_csr_is_veda_mepcc_base_a1 <= CPU_csr_is_veda_mepcc_base_a0;

      // Staging of $csr_is_veda_mepcc_length.
      always_ff @(posedge clk) CPU_csr_is_veda_mepcc_length_a1 <= CPU_csr_is_veda_mepcc_length_a0;

      // Staging of $csr_is_veda_pcc_base.
      always_ff @(posedge clk) CPU_csr_is_veda_pcc_base_a1 <= CPU_csr_is_veda_pcc_base_a0;

      // Staging of $csr_is_veda_pcc_length.
      always_ff @(posedge clk) CPU_csr_is_veda_pcc_length_a1 <= CPU_csr_is_veda_pcc_length_a0;

      // Staging of $csr_wdata.
      always_ff @(posedge clk) CPU_csr_wdata_a1[63:0] <= CPU_csr_wdata_a0[63:0];

      // Staging of $csr_write_en.
      always_ff @(posedge clk) CPU_csr_write_en_a1 <= CPU_csr_write_en_a0;

      // Staging of $cyc_cnt.
      always_ff @(posedge clk) CPU_cyc_cnt_a1[31:0] <= CPU_cyc_cnt_a0[31:0];

      // Staging of $dmem_new_word.
      always_ff @(posedge clk) CPU_dmem_new_word_a1[63:0] <= CPU_dmem_new_word_a0[63:0];

      // Staging of $is_store.
      always_ff @(posedge clk) CPU_is_store_a1 <= CPU_is_store_a0;

      // Staging of $is_veda_bind_notrap.
      always_ff @(posedge clk) CPU_is_veda_bind_notrap_a1 <= CPU_is_veda_bind_notrap_a0;

      // Staging of $is_veda_bind_plain.
      always_ff @(posedge clk) CPU_is_veda_bind_plain_a1 <= CPU_is_veda_bind_plain_a0;

      // Staging of $is_veda_cseal.
      always_ff @(posedge clk) CPU_is_veda_cseal_a1 <= CPU_is_veda_cseal_a0;

      // Staging of $is_veda_csetbounds_either.
      always_ff @(posedge clk) CPU_is_veda_csetbounds_either_a1 <= CPU_is_veda_csetbounds_either_a0;

      // Staging of $is_veda_cunseal.
      always_ff @(posedge clk) CPU_is_veda_cunseal_a1 <= CPU_is_veda_cunseal_a0;

      // Staging of $is_veda_droppriv.
      always_ff @(posedge clk) CPU_is_veda_droppriv_a1 <= CPU_is_veda_droppriv_a0;

      // Staging of $is_veda_oca.
      always_ff @(posedge clk) CPU_is_veda_oca_a1 <= CPU_is_veda_oca_a0;

      // Staging of $is_veda_ocinvoke.
      always_ff @(posedge clk) CPU_is_veda_ocinvoke_a1 <= CPU_is_veda_ocinvoke_a0;

      // Staging of $is_veda_ocl_c.
      always_ff @(posedge clk) CPU_is_veda_ocl_c_a1 <= CPU_is_veda_ocl_c_a0;

      // Staging of $is_veda_ospecialrw.
      always_ff @(posedge clk) CPU_is_veda_ospecialrw_a1 <= CPU_is_veda_ospecialrw_a0;

      // Staging of $is_veda_rebind.
      always_ff @(posedge clk) CPU_is_veda_rebind_a1 <= CPU_is_veda_rebind_a0;

      // Staging of $mcause.
      always_ff @(posedge clk) CPU_mcause_a1[63:0] <= CPU_mcause_a0[63:0];

      // Staging of $mem_word_idx.
      always_ff @(posedge clk) CPU_mem_word_idx_a1[5:0] <= CPU_mem_word_idx_a0[5:0];

      // Staging of $mepc.
      always_ff @(posedge clk) CPU_mepc_a1[63:0] <= CPU_mepc_a0[63:0];

      // Staging of $mtval.
      always_ff @(posedge clk) CPU_mtval_a1[63:0] <= CPU_mtval_a0[63:0];

      // Staging of $mtvec.
      always_ff @(posedge clk) CPU_mtvec_a1[63:0] <= CPU_mtvec_a0[63:0];

      // Staging of $pc.
      always_ff @(posedge clk) CPU_pc_a1[63:0] <= CPU_pc_a0[63:0];

      // Staging of $pc_src.
      always_ff @(posedge clk) CPU_pc_src_a1 <= CPU_pc_src_a0;

      // Staging of $priv.
      always_ff @(posedge clk) CPU_priv_a1 <= CPU_priv_a0;

      // Staging of $rd.
      always_ff @(posedge clk) CPU_rd_a1[4:0] <= CPU_rd_a0[4:0];

      // Staging of $reg_write.
      always_ff @(posedge clk) CPU_reg_write_a1 <= CPU_reg_write_a0;

      // Staging of $reset.
      always_ff @(posedge clk) CPU_reset_a1 <= CPU_reset_a0;

      // Staging of $veda_attr.
      always_ff @(posedge clk) CPU_veda_attr_a1[31:0] <= CPU_veda_attr_a0[31:0];

      // Staging of $veda_bind_trap.
      always_ff @(posedge clk) CPU_veda_bind_trap_a1 <= CPU_veda_bind_trap_a0;

      // Staging of $veda_cs2_base.
      always_ff @(posedge clk) CPU_veda_cs2_base_a1[31:0] <= CPU_veda_cs2_base_a0[31:0];

      // Staging of $veda_cs2_length.
      always_ff @(posedge clk) CPU_veda_cs2_length_a1[15:0] <= CPU_veda_cs2_length_a0[15:0];

      // Staging of $veda_cs2_object_id.
      always_ff @(posedge clk) CPU_veda_cs2_object_id_a1[22:0] <= CPU_veda_cs2_object_id_a0[22:0];

      // Staging of $veda_cs2_offset.
      always_ff @(posedge clk) CPU_veda_cs2_offset_a1[15:0] <= CPU_veda_cs2_offset_a0[15:0];

      // Staging of $veda_cs2_perms.
      always_ff @(posedge clk) CPU_veda_cs2_perms_a1[15:0] <= CPU_veda_cs2_perms_a0[15:0];

      // Staging of $veda_cs2_reserved.
      always_ff @(posedge clk) CPU_veda_cs2_reserved_a1[7:0] <= CPU_veda_cs2_reserved_a0[7:0];

      // Staging of $veda_cseal_ok.
      always_ff @(posedge clk) CPU_veda_cseal_ok_a1 <= CPU_veda_cseal_ok_a0;

      // Staging of $veda_csetbounds_new_base.
      always_ff @(posedge clk) CPU_veda_csetbounds_new_base_a1[31:0] <= CPU_veda_csetbounds_new_base_a0[31:0];

      // Staging of $veda_csetbounds_new_length.
      always_ff @(posedge clk) CPU_veda_csetbounds_new_length_a1[15:0] <= CPU_veda_csetbounds_new_length_a0[15:0];

      // Staging of $veda_csetbounds_ok.
      always_ff @(posedge clk) CPU_veda_csetbounds_ok_a1 <= CPU_veda_csetbounds_ok_a0;

      // Staging of $veda_cunseal_ok.
      always_ff @(posedge clk) CPU_veda_cunseal_ok_a1 <= CPU_veda_cunseal_ok_a0;

      // Staging of $veda_mepcc_base.
      always_ff @(posedge clk) CPU_veda_mepcc_base_a1[31:0] <= CPU_veda_mepcc_base_a0[31:0];

      // Staging of $veda_mepcc_length.
      always_ff @(posedge clk) CPU_veda_mepcc_length_a1[15:0] <= CPU_veda_mepcc_length_a0[15:0];

      // Staging of $veda_object_id.
      always_ff @(posedge clk) CPU_veda_object_id_a1[22:0] <= CPU_veda_object_id_a0[22:0];

      // Staging of $veda_oca_ok.
      always_ff @(posedge clk) CPU_veda_oca_ok_a1 <= CPU_veda_oca_ok_a0;

      // Staging of $veda_oca_sum.
      always_ff @(posedge clk) CPU_veda_oca_sum_a1[15:0] <= CPU_veda_oca_sum_a0[15:0];

      // Staging of $veda_ocinvoke_violation.
      always_ff @(posedge clk) CPU_veda_ocinvoke_violation_a1 <= CPU_veda_ocinvoke_violation_a0;

      // Staging of $veda_oclc_loaded_tag.
      always_ff @(posedge clk) CPU_veda_oclc_loaded_tag_a1 <= CPU_veda_oclc_loaded_tag_a0;

      // Staging of $veda_oclc_unpacked_base.
      always_ff @(posedge clk) CPU_veda_oclc_unpacked_base_a1[31:0] <= CPU_veda_oclc_unpacked_base_a0[31:0];

      // Staging of $veda_oclc_unpacked_length.
      always_ff @(posedge clk) CPU_veda_oclc_unpacked_length_a1[15:0] <= CPU_veda_oclc_unpacked_length_a0[15:0];

      // Staging of $veda_oclc_unpacked_object_id.
      always_ff @(posedge clk) CPU_veda_oclc_unpacked_object_id_a1[22:0] <= CPU_veda_oclc_unpacked_object_id_a0[22:0];

      // Staging of $veda_oclc_unpacked_offset.
      always_ff @(posedge clk) CPU_veda_oclc_unpacked_offset_a1[15:0] <= CPU_veda_oclc_unpacked_offset_a0[15:0];

      // Staging of $veda_oclc_unpacked_otype.
      always_ff @(posedge clk) CPU_veda_oclc_unpacked_otype_a1[15:0] <= CPU_veda_oclc_unpacked_otype_a0[15:0];

      // Staging of $veda_oclc_unpacked_perms.
      always_ff @(posedge clk) CPU_veda_oclc_unpacked_perms_a1[15:0] <= CPU_veda_oclc_unpacked_perms_a0[15:0];

      // Staging of $veda_oclc_unpacked_reserved.
      always_ff @(posedge clk) CPU_veda_oclc_unpacked_reserved_a1[7:0] <= CPU_veda_oclc_unpacked_reserved_a0[7:0];

      // Staging of $veda_oclc_violation.
      always_ff @(posedge clk) CPU_veda_oclc_violation_a1 <= CPU_veda_oclc_violation_a0;

      // Staging of $veda_oda_base.
      always_ff @(posedge clk) CPU_veda_oda_base_a1[31:0] <= CPU_veda_oda_base_a0[31:0];

      // Staging of $veda_oda_length.
      always_ff @(posedge clk) CPU_veda_oda_length_a1[15:0] <= CPU_veda_oda_length_a0[15:0];

      // Staging of $veda_oda_object_id.
      always_ff @(posedge clk) CPU_veda_oda_object_id_a1[22:0] <= CPU_veda_oda_object_id_a0[22:0];

      // Staging of $veda_oda_offset.
      always_ff @(posedge clk) CPU_veda_oda_offset_a1[15:0] <= CPU_veda_oda_offset_a0[15:0];

      // Staging of $veda_oda_otype.
      always_ff @(posedge clk) CPU_veda_oda_otype_a1[15:0] <= CPU_veda_oda_otype_a0[15:0];

      // Staging of $veda_oda_perms.
      always_ff @(posedge clk) CPU_veda_oda_perms_a1[15:0] <= CPU_veda_oda_perms_a0[15:0];

      // Staging of $veda_oda_reserved.
      always_ff @(posedge clk) CPU_veda_oda_reserved_a1[7:0] <= CPU_veda_oda_reserved_a0[7:0];

      // Staging of $veda_oda_tag.
      always_ff @(posedge clk) CPU_veda_oda_tag_a1 <= CPU_veda_oda_tag_a0;

      // Staging of $veda_odt_base.
      always_ff @(posedge clk) CPU_veda_odt_base_a1[31:0] <= CPU_veda_odt_base_a0[31:0];

      // Staging of $veda_odt_gen.
      always_ff @(posedge clk) CPU_veda_odt_gen_a1[7:0] <= CPU_veda_odt_gen_a0[7:0];

      // Staging of $veda_odt_length.
      always_ff @(posedge clk) CPU_veda_odt_length_a1[15:0] <= CPU_veda_odt_length_a0[15:0];

      // Staging of $veda_odt_perms.
      always_ff @(posedge clk) CPU_veda_odt_perms_a1[15:0] <= CPU_veda_odt_perms_a0[15:0];

      // Staging of $veda_odt_valid.
      always_ff @(posedge clk) CPU_veda_odt_valid_a1 <= CPU_veda_odt_valid_a0;

      // Staging of $veda_ospecialrw_violation.
      always_ff @(posedge clk) CPU_veda_ospecialrw_violation_a1 <= CPU_veda_ospecialrw_violation_a0;

      // Staging of $veda_owner_ok.
      always_ff @(posedge clk) CPU_veda_owner_ok_a1 <= CPU_veda_owner_ok_a0;

      // Staging of $veda_pcc_base.
      always_ff @(posedge clk) CPU_veda_pcc_base_a1[31:0] <= CPU_veda_pcc_base_a0[31:0];

      // Staging of $veda_pcc_length.
      always_ff @(posedge clk) CPU_veda_pcc_length_a1[15:0] <= CPU_veda_pcc_length_a0[15:0];

      // Staging of $veda_pcc_violation.
      always_ff @(posedge clk) CPU_veda_pcc_violation_a1 <= CPU_veda_pcc_violation_a0;

      // Staging of $veda_rd_cap.
      always_ff @(posedge clk) CPU_veda_rd_cap_a1[3:0] <= CPU_veda_rd_cap_a0[3:0];

      // Staging of $veda_rebind_ok.
      always_ff @(posedge clk) CPU_veda_rebind_ok_a1 <= CPU_veda_rebind_ok_a0;

      // Staging of $veda_rs1cap_base.
      always_ff @(posedge clk) CPU_veda_rs1cap_base_a1[31:0] <= CPU_veda_rs1cap_base_a0[31:0];

      // Staging of $veda_rs1cap_length.
      always_ff @(posedge clk) CPU_veda_rs1cap_length_a1[15:0] <= CPU_veda_rs1cap_length_a0[15:0];

      // Staging of $veda_rs1cap_object_id.
      always_ff @(posedge clk) CPU_veda_rs1cap_object_id_a1[22:0] <= CPU_veda_rs1cap_object_id_a0[22:0];

      // Staging of $veda_rs1cap_offset.
      always_ff @(posedge clk) CPU_veda_rs1cap_offset_a1[15:0] <= CPU_veda_rs1cap_offset_a0[15:0];

      // Staging of $veda_rs1cap_otype.
      always_ff @(posedge clk) CPU_veda_rs1cap_otype_a1[15:0] <= CPU_veda_rs1cap_otype_a0[15:0];

      // Staging of $veda_rs1cap_perms.
      always_ff @(posedge clk) CPU_veda_rs1cap_perms_a1[15:0] <= CPU_veda_rs1cap_perms_a0[15:0];

      // Staging of $veda_rs1cap_reserved.
      always_ff @(posedge clk) CPU_veda_rs1cap_reserved_a1[7:0] <= CPU_veda_rs1cap_reserved_a0[7:0];

      // Staging of $veda_rs1cap_tag.
      always_ff @(posedge clk) CPU_veda_rs1cap_tag_a1 <= CPU_veda_rs1cap_tag_a0;

      // Staging of $veda_trap_cap_idx.
      always_ff @(posedge clk) CPU_veda_trap_cap_idx_a1[3:0] <= CPU_veda_trap_cap_idx_a0[3:0];

      // Staging of $veda_trap_cause.
      always_ff @(posedge clk) CPU_veda_trap_cause_a1[4:0] <= CPU_veda_trap_cause_a0[4:0];

      // Staging of $veda_trap_taken.
      always_ff @(posedge clk) CPU_veda_trap_taken_a1 <= CPU_veda_trap_taken_a0;

      // Staging of $wr_data.
      always_ff @(posedge clk) CPU_wr_data_a1[63:0] <= CPU_wr_data_a0[63:0];


      //
      // Scope: /dmem[63:0]
      //
      for (dmem = 0; dmem <= 63; dmem++) begin : L1gen_CPU_Dmem
         // Staging of $val.
         always_ff @(posedge clk) CPU_Dmem_val_a1[dmem][63:0] <= CPU_Dmem_val_a0[dmem][63:0];

      end

      //
      // Scope: /vreg[15:0]
      //
      for (vreg = 0; vreg <= 15; vreg++) begin : L1gen_CPU_Vreg
         // Staging of $base.
         always_ff @(posedge clk) CPU_Vreg_base_a1[vreg][31:0] <= CPU_Vreg_base_a0[vreg][31:0];

         // Staging of $length.
         always_ff @(posedge clk) CPU_Vreg_length_a1[vreg][15:0] <= CPU_Vreg_length_a0[vreg][15:0];

         // Staging of $object_id.
         always_ff @(posedge clk) CPU_Vreg_object_id_a1[vreg][22:0] <= CPU_Vreg_object_id_a0[vreg][22:0];

         // Staging of $offset.
         always_ff @(posedge clk) CPU_Vreg_offset_a1[vreg][15:0] <= CPU_Vreg_offset_a0[vreg][15:0];

         // Staging of $otype.
         always_ff @(posedge clk) CPU_Vreg_otype_a1[vreg][15:0] <= CPU_Vreg_otype_a0[vreg][15:0];

         // Staging of $perms.
         always_ff @(posedge clk) CPU_Vreg_perms_a1[vreg][15:0] <= CPU_Vreg_perms_a0[vreg][15:0];

         // Staging of $reserved.
         always_ff @(posedge clk) CPU_Vreg_reserved_a1[vreg][7:0] <= CPU_Vreg_reserved_a0[vreg][7:0];

         // Staging of $tag.
         always_ff @(posedge clk) CPU_Vreg_tag_a1[vreg] <= CPU_Vreg_tag_a0[vreg];

      end

      //
      // Scope: /xreg[31:0]
      //
      for (xreg = 0; xreg <= 31; xreg++) begin : L1gen_CPU_Xreg
         // Staging of $val.
         always_ff @(posedge clk) CPU_Xreg_val_a1[xreg][63:0] <= CPU_Xreg_val_a0[xreg][63:0];

      end


